#!/usr/bin/env python3
"""Print canonical artifact or operation contracts as deterministic JSON."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from scripts.schemas.contracts import artifact_contract_for_type
from scripts.schemas.operations import OPERATION_CATALOG
from scripts.schemas.topic import TopicSchema


def _topic_outline_subquestions_schema() -> dict[str, object]:
    """Return the closed producer projection derived from TopicSchema."""

    root = TopicSchema.model_json_schema(mode="validation")
    definitions = root.get("$defs", {})

    def project(value: object) -> object:
        if isinstance(value, list):
            return [project(item) for item in value]
        if not isinstance(value, dict):
            return value
        if set(value) == {"$ref"}:
            prefix = "#/$defs/"
            ref = value["$ref"]
            if not isinstance(ref, str) or not ref.startswith(prefix):
                raise ValueError(f"unsupported Topic schema ref: {ref!r}")
            return project(definitions[ref.removeprefix(prefix)])
        result = {
            key: project(item)
            for key, item in value.items()
            if key not in {"default", "title"}
        }
        properties = result.get("properties")
        if result.get("type") == "object" and isinstance(properties, dict):
            result["required"] = list(properties)
        return result

    raw = root["properties"]["subquestions"]
    if not isinstance(raw, dict) or not isinstance(raw.get("anyOf"), list):
        raise ValueError("TopicSchema omitted nullable subquestions")
    array = next(
        branch
        for branch in raw["anyOf"]
        if isinstance(branch, dict) and branch.get("type") == "array"
    )
    projected = project(array)
    if not isinstance(projected, dict):
        raise ValueError("Topic subquestion projection is not an object")
    return projected


def _literal_union(values: list[str]) -> str:
    return " | ".join(json.dumps(value) for value in values) or "never"


def _typescript_declarations(types: list[str]) -> str:
    kinds = list(
        dict.fromkeys(
            kind
            for definition in OPERATION_CATALOG.values()
            for kind in definition["kinds"]
        )
    )
    operations = list(OPERATION_CATALOG)
    phases = list(
        dict.fromkeys(
            definition["phase"]
            for definition in OPERATION_CATALOG.values()
        )
    )
    contract_declarations = "\n".join(
        f"export const {type_name.upper()}_ARTIFACT_CONTRACT: ArtifactContract;"
        for type_name in types
    )
    return f'''// GENERATED by scripts/build-workflows.mjs. DO NOT EDIT.
// Source of truth: scripts/schemas/ frontmatter models, BodySchema, and operations.py.

export type KindName = {_literal_union(kinds)};
export type OperationName = {_literal_union(operations)};
export type PhaseName = {_literal_union(phases)};
export type EffectName = "readonly" | "writer";

export type WorkflowContext = Record<string, any>;
export type JsonSchema = Record<string, any>;
export interface ArtifactContract {{
  readonly artifact_type: string;
  readonly schema_version: string;
  readonly [key: string]: any;
}}
export interface ArtifactTemplates {{
  readonly [role: string]: string;
}}
export interface OperationDefinition {{
  readonly kinds: readonly KindName[];
  readonly phase: PhaseName;
  readonly effect: EffectName;
  readonly agent: string;
  readonly artifacts: ArtifactTemplates;
}}

export interface StageIssue {{
  code: string;
  operation: OperationName | string;
  summary: string;
  user_question: string | null;
  retryable: boolean;
}}
export interface StageTerminalPayload {{
  disposition?: string;
  source?: string;
  action?: string;
  write_state?: string;
}}
export type StageTerminal =
  | ({{ status: "complete"; issue: null }} & StageTerminalPayload)
  | ({{ status: "needs_input"; issue: StageIssue }} & StageTerminalPayload)
  | ({{ status: "blocked"; issue: StageIssue }} & StageTerminalPayload)
  | ({{ status: "failed"; issue: StageIssue }} & StageTerminalPayload);
export interface StageReceipt extends Record<string, any> {{
  terminal: StageTerminal;
}}

export type WriteTarget =
  | {{ scope: "exact"; path: string }}
  | {{ scope: "subtree"; path: string }};

export interface OperationRow {{
  readonly operation: OperationName;
  readonly context?: (
    rawContext: any,
    base: WorkflowContext,
  ) => WorkflowContext;
  readonly refs: (context: any) => WorkflowContext;
  readonly payloadProperties: (refs: any) => WorkflowContext;
  readonly terminalPayloads?: (refs: any) => WorkflowContext;
  readonly complete: (
    receipt: StageReceipt,
    context: any,
  ) => boolean;
  readonly envelope: (
    context: any,
    refs: any,
  ) => WorkflowContext;
  readonly promptText?: (request: any) => string;
  readonly writeTargets?: (
    refs: WorkflowContext,
    context: WorkflowContext,
  ) => readonly WriteTarget[];
}}
export interface OperationDescriptor extends OperationRow {{
  readonly stage: PhaseName;
  readonly effect: EffectName;
  readonly agentType: string;
  readonly artifacts: ArtifactTemplates;
}}

export const OPERATION_CATALOG: Readonly<
  Record<OperationName, OperationDefinition>
>;
export const TOPIC_OUTLINE_SUBQUESTIONS_SCHEMA: JsonSchema;
{contract_declarations}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--operations", action="store_true")
    mode.add_argument("--typescript", action="store_true")
    mode.add_argument("--topic-outline", action="store_true")
    parser.add_argument("types", nargs="*")
    args = parser.parse_args()
    if args.operations:
        if args.types:
            parser.error("--operations does not accept artifact types")
        print(
            json.dumps(
                OPERATION_CATALOG,
                ensure_ascii=False,
                separators=(",", ":"),
            )
        )
        return 0
    if args.typescript:
        if not args.types:
            parser.error("--typescript requires artifact types")
        for type_name in args.types:
            artifact_contract_for_type(type_name)
        print(_typescript_declarations(args.types), end="")
        return 0
    if args.topic_outline:
        if args.types:
            parser.error("--topic-outline does not accept artifact types")
        print(
            json.dumps(
                _topic_outline_subquestions_schema(),
                ensure_ascii=False,
                sort_keys=True,
                separators=(",", ":"),
            )
        )
        return 0
    if not args.types:
        parser.error("at least one artifact type is required")
    contracts = {
        type_name: artifact_contract_for_type(type_name)
        for type_name in args.types
    }
    print(
        json.dumps(
            contracts,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
