#!/usr/bin/env python3
"""Print canonical artifact contracts or the pipeline as deterministic JSON."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from scripts.schemas.contracts import artifact_contract_for_type
from scripts.schemas.pipeline import PIPELINE


def _literal_union(values: list[str]) -> str:
    return " | ".join(json.dumps(value) for value in values) or "never"


def _typescript_declarations(types: list[str]) -> str:
    stages = list(
        dict.fromkeys(
            stage["stage"]
            for definition in PIPELINE.values()
            for stage in definition["stages"]
        )
    )
    operations = list(
        dict.fromkeys(
            stage["operation"]
            for definition in PIPELINE.values()
            for stage in definition["stages"]
        )
    )
    phases = list(
        dict.fromkeys(
            stage["phase"]
            for definition in PIPELINE.values()
            for stage in definition["stages"]
        )
    )
    carries = [
        carry
        for definition in PIPELINE.values()
        for carry in definition.get("chain", {}).get("carries", [])
    ]
    carry_fields = list(dict.fromkeys(carry["field"] for carry in carries))
    carry_targets = list(dict.fromkeys(carry["to"] for carry in carries))
    contract_declarations = "\n".join(
        f"export const {type_name.upper()}_ARTIFACT_CONTRACT: ArtifactContract;"
        for type_name in types
    )
    return f'''// GENERATED by scripts/build-workflows.mjs. DO NOT EDIT.
// Source of truth: scripts/schemas/ frontmatter models, BodySchema, and pipeline.py.

export type KindName = {_literal_union(list(PIPELINE))};
export type StageName = {_literal_union(stages)};
export type OperationName = {_literal_union(operations)};
export type PhaseName = {_literal_union(phases)};
export type EffectName = "readonly" | "writer";
export type CarryFieldName = {_literal_union(carry_fields)};
export type CarryTargetName = {_literal_union(carry_targets)};

export type WorkflowContext = Record<string, any>;
export type JsonSchema = Record<string, any>;
export interface ArtifactContract {{
  readonly artifact_type: string;
  readonly schema_version: string;
  readonly [key: string]: any;
}}
export interface ArtifactTemplates {{
  readonly [role: string]: string;
}}
export interface PipelineCarry {{
  readonly from: StageName;
  readonly field: CarryFieldName;
  readonly to: CarryTargetName;
}}
export interface PipelineStage {{
  readonly stage: StageName;
  readonly operation: OperationName;
  readonly phase: PhaseName;
  readonly effect: EffectName;
  readonly agent: string;
  readonly artifacts?: ArtifactTemplates;
}}
export interface KindDefinition {{
  readonly stages: readonly PipelineStage[];
  readonly chain?: {{
    readonly sequence: readonly StageName[];
    readonly carries: readonly PipelineCarry[];
  }};
}}

export interface StageIssue {{
  code: string;
  operation: OperationName | string;
  summary: string;
  user_question: string | null;
  retryable: boolean;
}}
export interface StageTerminalPayload {{
  disposition?: string;
  source?: string;
  action?: string;
  write_state?: string;
}}
export type StageTerminal =
  | ({{ status: "complete"; issue: null }} & StageTerminalPayload)
  | ({{ status: "needs_input"; issue: StageIssue }} & StageTerminalPayload)
  | ({{ status: "blocked"; issue: StageIssue }} & StageTerminalPayload)
  | ({{ status: "failed"; issue: StageIssue }} & StageTerminalPayload);
export interface StageReceipt extends Record<string, any> {{
  terminal: StageTerminal;
}}

export type WriteTarget =
  | {{ scope: "exact"; path: string }}
  | {{ scope: "subtree"; path: string }};

export interface OperationRow {{
  readonly operation: OperationName;
  readonly context?: (
    rawContext: any,
    base: WorkflowContext,
  ) => WorkflowContext;
  readonly refs: (context: any) => WorkflowContext;
  readonly payloadProperties: (refs: any) => WorkflowContext;
  readonly terminalPayloads?: (refs: any) => WorkflowContext;
  readonly complete: (
    receipt: StageReceipt,
    context: any,
  ) => boolean;
  readonly envelope: (
    context: any,
    refs: any,
  ) => WorkflowContext;
  readonly promptText?: (request: any) => string;
  readonly writeTargets?: (
    refs: WorkflowContext,
    context: WorkflowContext,
  ) => readonly WriteTarget[];
}}
export interface OperationDescriptor extends OperationRow {{
  readonly stage: PhaseName;
  readonly effect: EffectName;
  readonly agentType: string;
  readonly artifacts: ArtifactTemplates;
}}

export const PIPELINE: Readonly<Record<KindName, KindDefinition>>;
{contract_declarations}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--pipeline", action="store_true")
    mode.add_argument("--typescript", action="store_true")
    parser.add_argument("types", nargs="*")
    args = parser.parse_args()
    if args.pipeline:
        if args.types:
            parser.error("--pipeline does not accept artifact types")
        print(
            json.dumps(
                PIPELINE,
                ensure_ascii=False,
                separators=(",", ":"),
            )
        )
        return 0
    if args.typescript:
        if not args.types:
            parser.error("--typescript requires artifact types")
        for type_name in args.types:
            artifact_contract_for_type(type_name)
        print(_typescript_declarations(args.types), end="")
        return 0
    if not args.types:
        parser.error("at least one artifact type is required")
    contracts = {
        type_name: artifact_contract_for_type(type_name)
        for type_name in args.types
    }
    print(
        json.dumps(
            contracts,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
