"""Canonical operation identity and artifact templates."""

OPERATION_CATALOG = {
    "webpage.identify": {
        "kinds": ["webpage"],
        "phase": "Search",
        "effect": "readonly",
        "agent": "quasi:webpage-agent",
        "artifacts": {},
    },
    "webpage.capture": {
        "kinds": ["webpage"],
        "phase": "Acquire",
        "effect": "writer",
        "agent": "quasi:webpage-agent",
        "artifacts": {"snapshot": "vault/webpages/{slug}/snapshot.webarchive"},
    },
    "webpage.prepare": {
        "kinds": ["webpage"],
        "phase": "Prepare",
        "effect": "writer",
        "agent": "quasi:webpage-agent",
        "artifacts": {
            "snapshot": "vault/webpages/{slug}/snapshot.webarchive",
            "output": "processing/webpages/{slug}/source.md",
        },
    },
    "webpage.analyse": {
        "kinds": ["webpage"],
        "phase": "Analyse",
        "effect": "writer",
        "agent": "quasi:analyse-agent",
        "artifacts": {"output": "vault/webpages/{slug}/webpage.md"},
    },
    "webpage.audit": {
        "kinds": ["webpage"],
        "phase": "Audit",
        "effect": "writer",
        "agent": "quasi:audit-agent",
        "artifacts": {"target": "vault/webpages/{slug}/webpage.md"},
    },
    "material.search": {
        "kinds": ["paper", "book"],
        "phase": "Search",
        "effect": "readonly",
        "agent": "quasi:metadata-agent",
        "artifacts": {},
    },
    "paper.acquire": {
        "kinds": ["paper"],
        "phase": "Acquire",
        "effect": "writer",
        "agent": "quasi:download-agent",
        "artifacts": {"output": "sources/{slug}.pdf"},
    },
    "paper.prepare": {
        "kinds": ["paper"],
        "phase": "Prepare",
        "effect": "writer",
        "agent": "quasi:extract-agent",
        "artifacts": {
            "source": "sources/{slug}.pdf",
            "normalized": "processing/papers/{slug}/source.txt",
            "recoverySource": "processing/papers/{slug}/ocr.pdf",
            "recoveryText": "processing/papers/{slug}/ocr.txt",
        },
    },
    "paper.analyse": {
        "kinds": ["paper"],
        "phase": "Analyse",
        "effect": "writer",
        "agent": "quasi:analyse-agent",
        "artifacts": {"output": "vault/papers/{slug}.md"},
    },
    "paper.audit": {
        "kinds": ["paper"],
        "phase": "Audit",
        "effect": "writer",
        "agent": "quasi:audit-agent",
        "artifacts": {"target": "vault/papers/{slug}.md"},
    },
    "book.acquire": {
        "kinds": ["book"],
        "phase": "Acquire",
        "effect": "writer",
        "agent": "quasi:download-agent",
        "artifacts": {},
    },
    "book.prepare": {
        "kinds": ["book"],
        "phase": "Prepare",
        "effect": "writer",
        "agent": "quasi:extract-agent",
        "artifacts": {
            "source": "sources/{slug}.{format}",
            "normalized": "processing/chapters/{slug}/source.txt",
            "recoverySource": "processing/chapters/{slug}/ocr.pdf",
            "recoveryText": "processing/chapters/{slug}/ocr.txt",
            "outputDir": "processing/chapters/{slug}",
            "manifest": "processing/chapters/{slug}/manifest.json",
        },
    },
    "chapter.analyse": {
        "kinds": ["book"],
        "phase": "Analyse",
        "effect": "writer",
        "agent": "quasi:analyse-agent",
        "artifacts": {},
    },
    "book.synthesise": {
        "kinds": ["book"],
        "phase": "Synthesise",
        "effect": "writer",
        "agent": "quasi:synthesis-agent",
        "artifacts": {"output": "vault/books/{slug}/00-overview.md"},
    },
    "book.audit": {
        "kinds": ["book"],
        "phase": "Audit",
        "effect": "writer",
        "agent": "quasi:audit-agent",
        "artifacts": {"target": "vault/books/{slug}"},
    },
    "talk.prepare": {
        "kinds": ["talk"],
        "phase": "Prepare",
        "effect": "writer",
        "agent": "quasi:transcribe-agent",
        "artifacts": {
            "processingDir": "processing/talks/{slug}",
            "manifest": "processing/talks/{slug}/manifest.json",
            "prepared": "vault/talks/{slug}/recording.mp4",
            "transcript": "vault/talks/{slug}/transcript.md",
            "subtitle": "vault/talks/{slug}/recording.srt",
            "canonical": "vault/talks/{slug}/talk.md",
        },
    },
    "talk.analyse": {
        "kinds": ["talk"],
        "phase": "Analyse",
        "effect": "writer",
        "agent": "quasi:analyse-agent",
        "artifacts": {"output": "vault/talks/{slug}/talk.md"},
    },
    "talk.audit": {
        "kinds": ["talk"],
        "phase": "Audit",
        "effect": "writer",
        "agent": "quasi:audit-agent",
        "artifacts": {"target": "vault/talks/{slug}/talk.md"},
    },
    "translation.prepare": {
        "kinds": ["translation"],
        "phase": "Prepare",
        "effect": "writer",
        "agent": "quasi:translate-agent",
        "artifacts": {
            "source": "sources/{slug}.pdf",
            "derivatives": "processing/translations/{slug}-*.pdf",
            "output": "processing/translations/{slug}-{target}.pdf",
            "manifest": "processing/translations/{slug}-{target}.manifest.json",
            "recoverySource": "processing/translations/{slug}-{target}-reocr.pdf",
        },
    },
    "topic.recall": {
        "kinds": ["topic"],
        "phase": "Recall",
        "effect": "readonly",
        "agent": "general-purpose",
        "artifacts": {},
    },
    "topic.steer": {
        "kinds": ["topic"],
        "phase": "Search",
        "effect": "writer",
        "agent": "quasi:steer-agent",
        "artifacts": {"outputPath": "vault/topics/{slug}/02-outline.md"},
    },
    "topic.webcard": {
        "kinds": ["topic"],
        "phase": "Search",
        "effect": "writer",
        "agent": "quasi:webcard-agent",
        "artifacts": {"cardPath": "vault/topics/{slug}/cards/{target}.md"},
    },
    "topic.synthesise.overview": {
        "kinds": ["topic"],
        "phase": "Synthesise",
        "effect": "writer",
        "agent": "quasi:synthesis-agent",
        "artifacts": {
            "outlinePath": "vault/topics/{slug}/02-outline.md",
            "outputPath": "vault/topics/{slug}/00-overview.md",
        },
    },
    "topic.synthesise.resources": {
        "kinds": ["topic"],
        "phase": "Synthesise",
        "effect": "writer",
        "agent": "quasi:synthesis-agent",
        "artifacts": {
            "outlinePath": "vault/topics/{slug}/02-outline.md",
            "outputPath": "vault/topics/{slug}/01-resources.md",
        },
    },
    "topic.audit": {
        "kinds": ["topic"],
        "phase": "Audit",
        "effect": "writer",
        "agent": "quasi:audit-agent",
        "artifacts": {"target": "{target}"},
    },
    "author.discover-books": {
        "kinds": ["author"],
        "phase": "Search",
        "effect": "readonly",
        "agent": "quasi:discovery-agent",
        "artifacts": {},
    },
    "author.discover-papers": {
        "kinds": ["author"],
        "phase": "Search",
        "effect": "readonly",
        "agent": "quasi:discovery-agent",
        "artifacts": {},
    },
    "author.resolve-membership": {
        "kinds": ["author"],
        "phase": "Search",
        "effect": "readonly",
        "agent": "general-purpose",
        "artifacts": {"output": "vault/authors/{slug}.md"},
    },
    "author.synthesise": {
        "kinds": ["author"],
        "phase": "Synthesise",
        "effect": "writer",
        "agent": "quasi:synthesis-agent",
        "artifacts": {"output": "vault/authors/{slug}.md"},
    },
    "author.audit": {
        "kinds": ["author"],
        "phase": "Audit",
        "effect": "writer",
        "agent": "quasi:audit-agent",
        "artifacts": {"target": "vault/authors/{slug}.md"},
    },
}
