// GENERATED by scripts/build-workflows.mjs. DO NOT EDIT.
// Source of truth: scripts/schemas/ frontmatter models, BodySchema, and pipeline.py.

export const AUTHOR_ARTIFACT_CONTRACT = {
  "artifact_type": "author",
  "document": {
    "additional_h2": false,
    "evidence_rules": [
      "只使用 caller 提供并验证的 canonical Book/Paper corpus",
      "每份成员作品首次出现时使用由其 exact canonical path 推导的 wikilink",
      "保持原材料的证据类型，不虚构时间顺序、引文或作品关系",
      "rating 只能由 caller 提供的证据支持；没有证据时省略"
    ],
    "h1": "使用 frontmatter.name",
    "metadata_lines": [],
    "section_order": [
      "思想肖像",
      "代表著作",
      "学术轨迹",
      "关键概念",
      "理论网络",
      "金句要点",
      "项目关联"
    ],
    "sections": [
      {
        "description": "2-3 句概括该学者的核心关切和贡献",
        "h2": "思想肖像",
        "kind": "paragraph",
        "required": true
      },
      {
        "description": "仅列专著;没有专著的作者跳过",
        "h2": "代表著作",
        "kind": "paragraph",
        "required": false
      },
      {
        "description": "学者的研究历程",
        "h2": "学术轨迹",
        "kind": "paragraph",
        "required": true
      },
      {
        "description": "该学者提出/常用的核心概念表",
        "h2": "关键概念",
        "kind": "table",
        "required": true
      },
      {
        "description": "该学者对话过的思想家、理论传统",
        "h2": "理论网络",
        "kind": "bullet-list",
        "required": true
      },
      {
        "description": "可引用的代表性论点 / 原文金句",
        "h2": "金句要点",
        "kind": "blockquote-list",
        "required": true
      },
      {
        "child_kind": "paragraph",
        "description": "H3 per project — 项目名作为 H3 标签;reader 渲染为 tabs",
        "h2": "项目关联",
        "kind": "h3-project-tabs",
        "required": true
      }
    ]
  },
  "frontmatter": {
    "field_order": [
      "type",
      "name",
      "themes",
      "topics",
      "rating"
    ],
    "json_schema": {
      "additionalProperties": false,
      "description": "Profile of a scholar. One file per author.",
      "properties": {
        "name": {
          "description": "作者全名,作为该 entity 的展示名",
          "maxLength": 120,
          "minLength": 2,
          "title": "Name",
          "type": "string"
        },
        "rating": {
          "anyOf": [
            {
              "maximum": 5,
              "minimum": 1,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "整体学术评分(1..5,reader 渲染为 ★);可选",
          "title": "Rating"
        },
        "themes": {
          "description": "研究方向标签数组;允许空但 lint warn '0 themes 可能漏写'",
          "items": {
            "type": "string"
          },
          "title": "Themes",
          "type": "array"
        },
        "topics": {
          "description": "所属 topic 语料的 slug 数组;供前端按成员反查;允许空",
          "items": {
            "type": "string"
          },
          "title": "Topics",
          "type": "array"
        },
        "type": {
          "const": "author",
          "description": "类型判别符,固定为字面量 'author'",
          "title": "Type",
          "type": "string"
        }
      },
      "required": [
        "type",
        "name"
      ],
      "title": "AuthorSchema",
      "type": "object"
    }
  },
  "identity": {
    "fields": [
      "name"
    ],
    "properties": {
      "name": {
        "description": "作者全名,作为该 entity 的展示名",
        "maxLength": 120,
        "minLength": 2,
        "title": "Name",
        "type": "string"
      }
    },
    "required": [
      "name"
    ]
  },
  "path_pattern": "vault/authors/{slug}.md",
  "schema_version": "quasi.artifact.author/0.1"
};

export const PAPER_ARTIFACT_CONTRACT = {
  "artifact_type": "paper",
  "document": {
    "additional_h2": false,
    "evidence_rules": [],
    "h1": "忠实概括论文标题；不添加装饰性或项目式后缀",
    "metadata_lines": [
      "英文原标题",
      "作者",
      "期刊来源",
      "仅在 identity 提供 DOI 时写 DOI"
    ],
    "section_order": [
      "核心论点",
      "理论框架",
      "分节摘要",
      "关键概念",
      "核心引用",
      "金句要点",
      "项目关联"
    ],
    "sections": [
      {
        "description": "说明研究问题、中心论点、证据、推理、贡献，以及正文实际提出的限制",
        "h2": "核心论点",
        "kind": "paragraph",
        "required": true
      },
      {
        "description": "理论传统、对话学者和思想资源",
        "h2": "理论框架",
        "kind": "paragraph",
        "required": true
      },
      {
        "child_kind": "paragraph",
        "description": "按原文小节结构 — H3 是原文 sub-section 标题",
        "h2": "分节摘要",
        "kind": "h3-sections",
        "required": true
      },
      {
        "columns": [
          "概念",
          "英文",
          "提出者",
          "定义"
        ],
        "description": "论文中讨论的核心概念(同名 H2,paper 用 table)",
        "h2": "关键概念",
        "kind": "table",
        "recommended_items": {
          "max": 5,
          "min": 3
        },
        "required": true
      },
      {
        "description": "论文实质使用的著作及其在论证中的作用；不补写 input 无法支持的书目信息",
        "h2": "核心引用",
        "kind": "numbered-list",
        "recommended_items": {
          "max": 15,
          "min": 5
        },
        "required": true
      },
      {
        "condition": "只有 input 中存在可定位的准确引文时才生成",
        "description": "可引用段落 / 原文金句",
        "h2": "金句要点",
        "kind": "blockquote-list",
        "required": false
      },
      {
        "child_kind": "numbered-list",
        "condition": "只有 caller identity 明确提供项目语境时才生成",
        "description": "",
        "h2": "项目关联",
        "kind": "h3-project-tabs",
        "required": false
      }
    ]
  },
  "frontmatter": {
    "field_order": [
      "type",
      "title",
      "authors",
      "year",
      "journal",
      "themes",
      "doi",
      "topics",
      "rating"
    ],
    "json_schema": {
      "additionalProperties": false,
      "description": "A journal article analysis.",
      "properties": {
        "authors": {
          "description": "作者数组,永远 ≥1 元素",
          "items": {
            "maxLength": 120,
            "minLength": 2,
            "type": "string"
          },
          "minItems": 1,
          "title": "Authors",
          "type": "array"
        },
        "doi": {
          "anyOf": [
            {
              "pattern": "^10\\.\\d+/.+",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Doi"
        },
        "journal": {
          "description": "期刊名;paper = 期刊论文,必填",
          "maxLength": 200,
          "minLength": 2,
          "title": "Journal",
          "type": "string"
        },
        "rating": {
          "anyOf": [
            {
              "maximum": 5,
              "minimum": 1,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Rating"
        },
        "themes": {
          "description": "主题标签数组;paper 必须有主题(不允许空 — 与 chapter 不同)",
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "title": "Themes",
          "type": "array"
        },
        "title": {
          "maxLength": 280,
          "minLength": 2,
          "title": "Title",
          "type": "string"
        },
        "topics": {
          "description": "所属 topic 语料的 slug 数组;供前端按成员反查;允许空",
          "items": {
            "type": "string"
          },
          "title": "Topics",
          "type": "array"
        },
        "type": {
          "const": "paper",
          "title": "Type",
          "type": "string"
        },
        "year": {
          "anyOf": [
            {
              "maximum": 2030,
              "minimum": 1500,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "description": "发表年",
          "title": "Year"
        }
      },
      "required": [
        "type",
        "title",
        "authors",
        "year",
        "journal",
        "themes"
      ],
      "title": "PaperSchema",
      "type": "object"
    }
  },
  "identity": {
    "fields": [
      "title",
      "authors",
      "year",
      "journal",
      "doi"
    ],
    "properties": {
      "authors": {
        "description": "作者数组,永远 ≥1 元素",
        "items": {
          "maxLength": 120,
          "minLength": 2,
          "type": "string"
        },
        "minItems": 1,
        "title": "Authors",
        "type": "array"
      },
      "doi": {
        "anyOf": [
          {
            "pattern": "^10\\.\\d+/.+",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Doi"
      },
      "journal": {
        "description": "期刊名;paper = 期刊论文,必填",
        "maxLength": 200,
        "minLength": 2,
        "title": "Journal",
        "type": "string"
      },
      "title": {
        "maxLength": 280,
        "minLength": 2,
        "title": "Title",
        "type": "string"
      },
      "year": {
        "anyOf": [
          {
            "maximum": 2030,
            "minimum": 1500,
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "description": "发表年",
        "title": "Year"
      }
    },
    "required": [
      "title",
      "authors",
      "year",
      "journal"
    ]
  },
  "path_pattern": "vault/papers/{slug}.md",
  "schema_version": "quasi.artifact.paper/0.1"
};

export const CHAPTER_ARTIFACT_CONTRACT = {
  "artifact_type": "chapter",
  "document": {
    "additional_h2": false,
    "evidence_rules": [],
    "h1": "忠实呈现 caller identity 中的 chapter label 与 chapter title，不添加装饰性后缀",
    "metadata_lines": [
      "可写原文标题、作者和关键词；每一项必须由 input 或 caller identity 支持"
    ],
    "section_order": [
      "核心论点",
      "理论框架",
      "分节摘要",
      "关键概念",
      "核心引用",
      "金句要点",
      "项目关联"
    ],
    "sections": [
      {
        "description": "章节的中心论点和论证逻辑",
        "h2": "核心论点",
        "kind": "paragraph",
        "required": true
      },
      {
        "description": "理论传统、对话学者和思想资源",
        "h2": "理论框架",
        "kind": "paragraph",
        "required": true
      },
      {
        "child_kind": "paragraph",
        "description": "按原文小节结构 — H3 是原文 sub-section 标题",
        "h2": "分节摘要",
        "kind": "h3-sections",
        "required": true
      },
      {
        "columns": [
          "概念",
          "英文",
          "提出者",
          "定义"
        ],
        "description": "章节中讨论的核心概念(同名 H2,chapter 用 table)",
        "h2": "关键概念",
        "kind": "table",
        "recommended_items": {
          "max": 5,
          "min": 3
        },
        "required": true
      },
      {
        "description": "本章实质使用的著作及其在论证中的作用；不补写 input 无法支持的书目信息",
        "h2": "核心引用",
        "kind": "numbered-list",
        "recommended_items": {
          "max": 15,
          "min": 5
        },
        "required": true
      },
      {
        "condition": "只有 input 中存在可定位的准确引文时才生成",
        "description": "可引用段落 / 原文金句",
        "h2": "金句要点",
        "kind": "blockquote-list",
        "required": false
      },
      {
        "child_kind": "numbered-list",
        "condition": "只有 caller identity 明确提供项目语境时才生成",
        "description": "",
        "h2": "项目关联",
        "kind": "h3-project-tabs",
        "required": false
      }
    ]
  },
  "frontmatter": {
    "field_order": [
      "type",
      "title",
      "authors",
      "year",
      "book",
      "themes",
      "topics",
      "rating"
    ],
    "json_schema": {
      "additionalProperties": false,
      "description": "A chapter analysis. Must live under vault/books/<slug>/.",
      "properties": {
        "authors": {
          "description": "章作者;编纂本里可与父书 authors 不同(章节作者 != 书编者)",
          "items": {
            "maxLength": 120,
            "minLength": 2,
            "type": "string"
          },
          "minItems": 1,
          "title": "Authors",
          "type": "array"
        },
        "book": {
          "description": "父书 slug(从文件路径派生,如 'allison-nightwork-1994');vault-wide lint 校验该 slug 真的存在对应的 book 文件",
          "maxLength": 200,
          "minLength": 2,
          "title": "Book",
          "type": "string"
        },
        "rating": {
          "anyOf": [
            {
              "maximum": 5,
              "minimum": 1,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Rating"
        },
        "themes": {
          "description": "章节级主题;允许空(章节经常没有独立主题标签)",
          "items": {
            "type": "string"
          },
          "title": "Themes",
          "type": "array"
        },
        "title": {
          "description": "章节标题(含 '第N章 XXX' 前缀)",
          "maxLength": 280,
          "minLength": 2,
          "title": "Title",
          "type": "string"
        },
        "topics": {
          "description": "所属 topic 语料的 slug 数组;供前端按成员反查;允许空",
          "items": {
            "type": "string"
          },
          "title": "Topics",
          "type": "array"
        },
        "type": {
          "const": "chapter",
          "title": "Type",
          "type": "string"
        },
        "year": {
          "anyOf": [
            {
              "maximum": 2030,
              "minimum": 1500,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "description": "通常等于父书 year",
          "title": "Year"
        }
      },
      "required": [
        "type",
        "title",
        "authors",
        "year",
        "book"
      ],
      "title": "ChapterSchema",
      "type": "object"
    }
  },
  "identity": {
    "fields": [
      "title",
      "authors",
      "year",
      "book"
    ],
    "properties": {
      "authors": {
        "description": "章作者;编纂本里可与父书 authors 不同(章节作者 != 书编者)",
        "items": {
          "maxLength": 120,
          "minLength": 2,
          "type": "string"
        },
        "minItems": 1,
        "title": "Authors",
        "type": "array"
      },
      "book": {
        "description": "父书 slug(从文件路径派生,如 'allison-nightwork-1994');vault-wide lint 校验该 slug 真的存在对应的 book 文件",
        "maxLength": 200,
        "minLength": 2,
        "title": "Book",
        "type": "string"
      },
      "title": {
        "description": "章节标题(含 '第N章 XXX' 前缀)",
        "maxLength": 280,
        "minLength": 2,
        "title": "Title",
        "type": "string"
      },
      "year": {
        "anyOf": [
          {
            "maximum": 2030,
            "minimum": 1500,
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "description": "通常等于父书 year",
        "title": "Year"
      }
    },
    "required": [
      "title",
      "authors",
      "year",
      "book"
    ]
  },
  "path_pattern": "vault/books/{book_slug}/ch{slot}-{chapter_slug}.md",
  "schema_version": "quasi.artifact.chapter/0.1"
};

export const BOOK_ARTIFACT_CONTRACT = {
  "artifact_type": "book",
  "document": {
    "additional_h2": false,
    "evidence_rules": [],
    "h1": "使用 frontmatter.title；不添加模板式或项目式后缀",
    "metadata_lines": [],
    "section_order": [
      "核心论点",
      "章节逻辑",
      "关键概念",
      "理论贡献",
      "精读章节",
      "项目关联"
    ],
    "sections": [
      {
        "description": "综合全部 supplied chapter analyses，说明全书的中心主题、核心论证和证据关系",
        "h2": "核心论点",
        "kind": "paragraph",
        "required": true
      },
      {
        "description": "各章如何构成整体论证;章节间递进/对话/互补关系",
        "h2": "章节逻辑",
        "kind": "paragraph",
        "required": true
      },
      {
        "columns": [
          "概念",
          "英文",
          "提出者",
          "定义"
        ],
        "description": "全书的核心概念表(同名 H2,book 用 table 形态)",
        "h2": "关键概念",
        "kind": "table",
        "required": true
      },
      {
        "description": "本书对学术领域的整体贡献",
        "h2": "理论贡献",
        "kind": "paragraph",
        "required": true
      },
      {
        "condition": "只推荐 supplied chapter analyses 中实际存在的章节",
        "description": "按优先级排序的推荐精读章节",
        "h2": "精读章节",
        "kind": "numbered-list",
        "required": true
      },
      {
        "child_kind": "paragraph",
        "condition": "只有 caller identity 明确提供项目语境时才生成",
        "description": "",
        "h2": "项目关联",
        "kind": "h3-project-tabs",
        "required": false
      }
    ]
  },
  "frontmatter": {
    "field_order": [
      "type",
      "title",
      "authors",
      "year",
      "publisher",
      "isbn",
      "doi",
      "category",
      "themes",
      "topics",
      "rating"
    ],
    "json_schema": {
      "additionalProperties": false,
      "description": "Analytical overview of a book. Aligns with BibTeX @book / @collection.",
      "properties": {
        "authors": {
          "description": "作者或编者数组;角色由 category 区分;永远数组(单作者也包成 1 元素)",
          "items": {
            "maxLength": 120,
            "minLength": 2,
            "type": "string"
          },
          "minItems": 1,
          "title": "Authors",
          "type": "array"
        },
        "category": {
          "default": "monograph",
          "description": "书籍类别;BibTeX export 时驱动 @book vs @collection + author vs editor",
          "enum": [
            "monograph",
            "edited-volume",
            "handbook",
            "other"
          ],
          "title": "Category",
          "type": "string"
        },
        "doi": {
          "anyOf": [
            {
              "pattern": "^10\\.\\d+/.+",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Doi"
        },
        "isbn": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "ISBN;接受 int|str,coerce 为 str;格式校验留给 lint",
          "title": "Isbn"
        },
        "publisher": {
          "description": "出版社;Phase 1 lint warn,Phase 2 严格必填",
          "maxLength": 200,
          "minLength": 2,
          "title": "Publisher",
          "type": "string"
        },
        "rating": {
          "anyOf": [
            {
              "maximum": 5,
              "minimum": 1,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Rating"
        },
        "themes": {
          "description": "主题标签数组",
          "items": {
            "type": "string"
          },
          "title": "Themes",
          "type": "array"
        },
        "title": {
          "description": "书名(含副标题)",
          "maxLength": 280,
          "minLength": 2,
          "title": "Title",
          "type": "string"
        },
        "topics": {
          "description": "所属 topic 语料的 slug 数组;供前端按成员反查;允许空",
          "items": {
            "type": "string"
          },
          "title": "Topics",
          "type": "array"
        },
        "type": {
          "const": "book",
          "title": "Type",
          "type": "string"
        },
        "year": {
          "anyOf": [
            {
              "maximum": 2030,
              "minimum": 1500,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "description": "出版年",
          "title": "Year"
        }
      },
      "required": [
        "type",
        "title",
        "authors",
        "year",
        "publisher"
      ],
      "title": "BookSchema",
      "type": "object"
    }
  },
  "identity": {
    "fields": [
      "title",
      "authors",
      "year",
      "publisher",
      "isbn",
      "category"
    ],
    "properties": {
      "authors": {
        "description": "作者或编者数组;角色由 category 区分;永远数组(单作者也包成 1 元素)",
        "items": {
          "maxLength": 120,
          "minLength": 2,
          "type": "string"
        },
        "minItems": 1,
        "title": "Authors",
        "type": "array"
      },
      "category": {
        "default": "monograph",
        "description": "书籍类别;BibTeX export 时驱动 @book vs @collection + author vs editor",
        "enum": [
          "monograph",
          "edited-volume",
          "handbook",
          "other"
        ],
        "title": "Category",
        "type": "string"
      },
      "isbn": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "ISBN;接受 int|str,coerce 为 str;格式校验留给 lint",
        "title": "Isbn"
      },
      "publisher": {
        "description": "出版社;Phase 1 lint warn,Phase 2 严格必填",
        "maxLength": 200,
        "minLength": 2,
        "title": "Publisher",
        "type": "string"
      },
      "title": {
        "description": "书名(含副标题)",
        "maxLength": 280,
        "minLength": 2,
        "title": "Title",
        "type": "string"
      },
      "year": {
        "anyOf": [
          {
            "maximum": 2030,
            "minimum": 1500,
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "description": "出版年",
        "title": "Year"
      }
    },
    "required": [
      "title",
      "authors",
      "year",
      "publisher"
    ]
  },
  "path_pattern": "vault/books/{slug}/00-overview.md",
  "schema_version": "quasi.artifact.book/0.1"
};

export const TALK_ARTIFACT_CONTRACT = {
  "artifact_type": "talk",
  "document": {
    "additional_h2": false,
    "evidence_rules": [],
    "h1": "使用 frontmatter.title",
    "metadata_lines": [
      "讲者",
      "日期",
      "场合",
      "时长",
      "transcript 未说明的非必填展示项标为（未说明）"
    ],
    "section_order": [
      "核心论点",
      "分节摘要",
      "关键概念",
      "项目关联",
      "文献人物",
      "时间脉络"
    ],
    "sections": [
      {
        "description": "这场讲座的中心主张、问题意识、贡献(2-4 段)",
        "h2": "核心论点",
        "kind": "paragraph",
        "required": true
      },
      {
        "child_kind": "paragraph",
        "description": "按内容实质分节(H3 小标题);摘要主体;问答并入此处;live talk 的每个 H3 下首行严格为「时间：`[mm:ss]`–`[mm:ss]`」,起止点逐项对照 transcript evidence 的实际发言范围核定,反引号必须按字面保留;超过一小时用 `[h:mm:ss]`",
        "h2": "分节摘要",
        "kind": "h3-sections",
        "required": true
      },
      {
        "columns": [
          "概念",
          "英文",
          "定义"
        ],
        "description": "讲座提出/反复使用的核心概念表;无则保留表头写一行",
        "h2": "关键概念",
        "kind": "table",
        "required": true
      },
      {
        "description": "与 vault/authors、BTS 综述议题、同系列讲座的关联;无则写「（暂无)」",
        "h2": "项目关联",
        "kind": "bullet-list",
        "required": true
      },
      {
        "description": "讲座点到的学者、著作、概念来源(列表);无则写一行说明",
        "h2": "文献人物",
        "kind": "bullet-list",
        "required": true
      },
      {
        "description": "详尽视频时间索引(talk 专属,置末,粒度细于分节摘要,不得用分节起止范围替代);每行严格为「- `[mm:ss]` 主题 — 概括」,时间戳取自 transcript,反引号必须按字面保留在输出里(播放器定位依赖它);超过一小时用 `[h:mm:ss]`",
        "h2": "时间脉络",
        "kind": "bullet-list",
        "required": true
      }
    ]
  },
  "frontmatter": {
    "field_order": [
      "type",
      "title",
      "date",
      "speaker",
      "themes",
      "rating",
      "media"
    ],
    "json_schema": {
      "additionalProperties": false,
      "description": "A talk / lecture recording analysis.",
      "properties": {
        "date": {
          "description": "录制日期(整日 ISO,如 2024-11-08)",
          "format": "date",
          "title": "Date",
          "type": "string"
        },
        "media": {
          "description": "媒体文件名,如 recording.mov(gitignore)",
          "maxLength": 200,
          "minLength": 2,
          "title": "Media",
          "type": "string"
        },
        "rating": {
          "anyOf": [
            {
              "maximum": 5,
              "minimum": 1,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Rating"
        },
        "speaker": {
          "description": "讲者姓名数组(可关联 vault/authors/);抽不到留空(省略整键)",
          "items": {
            "maxLength": 120,
            "minLength": 2,
            "type": "string"
          },
          "title": "Speaker",
          "type": "array"
        },
        "themes": {
          "description": "主题标签数组(复用全库 themes 词表);静音/失败录制可空",
          "items": {
            "type": "string"
          },
          "title": "Themes",
          "type": "array"
        },
        "title": {
          "maxLength": 280,
          "minLength": 2,
          "title": "Title",
          "type": "string"
        },
        "type": {
          "const": "talk",
          "title": "Type",
          "type": "string"
        }
      },
      "required": [
        "type",
        "title",
        "date",
        "media"
      ],
      "title": "TalkSchema",
      "type": "object"
    }
  },
  "identity": {
    "fields": [
      "title",
      "date",
      "media"
    ],
    "properties": {
      "date": {
        "description": "录制日期(整日 ISO,如 2024-11-08)",
        "format": "date",
        "title": "Date",
        "type": "string"
      },
      "media": {
        "description": "媒体文件名,如 recording.mov(gitignore)",
        "maxLength": 200,
        "minLength": 2,
        "title": "Media",
        "type": "string"
      },
      "title": {
        "maxLength": 280,
        "minLength": 2,
        "title": "Title",
        "type": "string"
      }
    },
    "required": [
      "title",
      "date",
      "media"
    ]
  },
  "path_pattern": "vault/talks/{slug}/talk.md",
  "schema_version": "quasi.artifact.talk/0.1"
};

export const PIPELINE = {
  "paper": {
    "stages": [
      {
        "stage": "search",
        "operation": "material.search",
        "phase": "Search",
        "effect": "readonly",
        "agent": "quasi:metadata-agent"
      },
      {
        "stage": "acquire",
        "operation": "paper.acquire",
        "phase": "Acquire",
        "effect": "writer",
        "agent": "quasi:download-agent"
      },
      {
        "stage": "prepare",
        "operation": "paper.prepare",
        "phase": "Prepare",
        "effect": "writer",
        "agent": "quasi:extract-agent"
      },
      {
        "stage": "analyse",
        "operation": "paper.analyse",
        "phase": "Analyse",
        "effect": "writer",
        "agent": "quasi:analyse-agent"
      },
      {
        "stage": "audit",
        "operation": "paper.audit",
        "phase": "Audit",
        "effect": "writer",
        "agent": "quasi:audit-agent"
      }
    ],
    "chain": {
      "sequence": [
        "acquire",
        "prepare",
        "analyse",
        "audit"
      ],
      "carries": [
        {
          "from": "prepare",
          "field": "selected_input",
          "to": "input"
        }
      ]
    }
  },
  "book": {
    "stages": [
      {
        "stage": "search",
        "operation": "material.search",
        "phase": "Search",
        "effect": "readonly",
        "agent": "quasi:metadata-agent"
      },
      {
        "stage": "acquire",
        "operation": "book.acquire",
        "phase": "Acquire",
        "effect": "writer",
        "agent": "quasi:download-agent"
      },
      {
        "stage": "prepare",
        "operation": "book.prepare",
        "phase": "Prepare",
        "effect": "writer",
        "agent": "quasi:extract-agent"
      },
      {
        "stage": "analyse",
        "operation": "chapter.analyse",
        "phase": "Analyse",
        "effect": "writer",
        "agent": "quasi:analyse-agent"
      },
      {
        "stage": "synthesise",
        "operation": "book.synthesise",
        "phase": "Synthesise",
        "effect": "writer",
        "agent": "quasi:synthesis-agent"
      },
      {
        "stage": "audit",
        "operation": "book.audit",
        "phase": "Audit",
        "effect": "writer",
        "agent": "quasi:audit-agent"
      }
    ]
  },
  "talk": {
    "stages": [
      {
        "stage": "prepare",
        "operation": "talk.prepare",
        "phase": "Prepare",
        "effect": "writer",
        "agent": "quasi:transcribe-agent"
      },
      {
        "stage": "analyse",
        "operation": "talk.analyse",
        "phase": "Analyse",
        "effect": "writer",
        "agent": "quasi:analyse-agent"
      },
      {
        "stage": "audit",
        "operation": "talk.audit",
        "phase": "Audit",
        "effect": "writer",
        "agent": "quasi:audit-agent"
      }
    ]
  },
  "translation": {
    "stages": [
      {
        "stage": "prepare",
        "operation": "translation.prepare",
        "phase": "Prepare",
        "effect": "writer",
        "agent": "quasi:translate-agent"
      }
    ]
  },
  "topic": {
    "stages": [
      {
        "stage": "recall",
        "operation": "topic.recall",
        "phase": "Recall",
        "effect": "readonly",
        "agent": "general-purpose"
      },
      {
        "stage": "steer",
        "operation": "topic.steer",
        "phase": "Search",
        "effect": "writer",
        "agent": "quasi:steer-agent"
      },
      {
        "stage": "webcard",
        "operation": "topic.webcard",
        "phase": "Search",
        "effect": "writer",
        "agent": "quasi:webcard-agent"
      },
      {
        "stage": "synthesise-overview",
        "operation": "topic.synthesise.overview",
        "phase": "Synthesise",
        "effect": "writer",
        "agent": "quasi:synthesis-agent"
      },
      {
        "stage": "synthesise-resources",
        "operation": "topic.synthesise.resources",
        "phase": "Synthesise",
        "effect": "writer",
        "agent": "quasi:synthesis-agent"
      },
      {
        "stage": "audit",
        "operation": "topic.audit",
        "phase": "Audit",
        "effect": "writer",
        "agent": "quasi:audit-agent"
      }
    ]
  },
  "author": {
    "stages": [
      {
        "stage": "discover-books",
        "operation": "author.discover-books",
        "phase": "Search",
        "effect": "readonly",
        "agent": "quasi:discovery-agent"
      },
      {
        "stage": "discover-papers",
        "operation": "author.discover-papers",
        "phase": "Search",
        "effect": "readonly",
        "agent": "quasi:discovery-agent"
      },
      {
        "stage": "resolve-membership",
        "operation": "author.resolve-membership",
        "phase": "Search",
        "effect": "readonly",
        "agent": "general-purpose"
      },
      {
        "stage": "synthesise",
        "operation": "author.synthesise",
        "phase": "Synthesise",
        "effect": "writer",
        "agent": "quasi:synthesis-agent"
      },
      {
        "stage": "audit",
        "operation": "author.audit",
        "phase": "Audit",
        "effect": "writer",
        "agent": "quasi:audit-agent"
      }
    ]
  }
};
