// GENERATED by scripts/build-workflows.mjs. DO NOT EDIT.
// Source of truth: scripts/schemas/ frontmatter models, BodySchema, and operations.py.

export const TOPIC_ARTIFACT_CONTRACT = {
  "artifact_type": "topic",
  "document": {
    "additional_h2": true,
    "evidence_rules": [
      "所有 Topic 页使用 type: topic；kind 必须匹配请求的 output role：overview/resources/outline/card",
      "frontmatter 只允许 JSON Schema 声明的字段；请求的 research_key、topic_slug、query 等编排字段不写入产物",
      "outline 必须有非空 subquestions，id 唯一；subquestions/history 仅用于 outline",
      "outline.items 只登记请求已接纳的 Book/Paper/Talk；cards 只登记已提供的证据卡，不以待办需求充当证据",
      "created/themes/archives 仅用于 card；archives 不重复，新的 Archive 证据卡按请求记录 exact Archive paths",
      "保留已有用户组织与正文内容；按合法 schema 修正元数据，不把旧的非法字段当作新格式依据"
    ],
    "h1": "使用 frontmatter.title",
    "metadata_lines": [],
    "section_order": [],
    "sections": []
  },
  "frontmatter": {
    "field_order": [
      "type",
      "title",
      "kind",
      "subquestions",
      "history",
      "created",
      "themes",
      "archives"
    ],
    "json_schema": {
      "$defs": {
        "SubqItem": {
          "additionalProperties": false,
          "description": "子问题的一个学术语料成员(持久在 outline frontmatter,跨轮跨重跑累计)。\n\n只收 vault 分析件(book/paper/talk)。圈外证据卡走 `Subquestion.cards`\n独立通道 —— 卡不是分析件,混进来会让 synth 按分析件路径去读一个不存在的产物。",
          "properties": {
            "kind": {
              "enum": [
                "book",
                "paper",
                "talk"
              ],
              "title": "Kind",
              "type": "string"
            },
            "role": {
              "anyOf": [
                {
                  "enum": [
                    "evidence",
                    "theory",
                    "method",
                    "context"
                  ],
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Role"
            },
            "slug": {
              "maxLength": 80,
              "minLength": 1,
              "pattern": "^[a-z0-9][a-z0-9-]{0,79}$",
              "title": "Slug",
              "type": "string"
            }
          },
          "required": [
            "kind",
            "slug"
          ],
          "title": "SubqItem",
          "type": "object"
        },
        "Subquestion": {
          "additionalProperties": false,
          "description": "研究大纲里的一个子问题(仅 kind: outline 页携带)。",
          "properties": {
            "cards": {
              "description": "证据卡 slug 表(cards/{slug}.md),与 items 平行的圈外证据通道",
              "items": {
                "maxLength": 80,
                "minLength": 2,
                "pattern": "^[a-z0-9][a-z0-9-]*$",
                "type": "string"
              },
              "maxItems": 50,
              "title": "Cards",
              "type": "array"
            },
            "channel": {
              "default": "academic",
              "enum": [
                "academic",
                "web",
                "mixed"
              ],
              "title": "Channel",
              "type": "string"
            },
            "coverage": {
              "enum": [
                "gap",
                "thin",
                "covered",
                "saturated"
              ],
              "title": "Coverage",
              "type": "string"
            },
            "id": {
              "maxLength": 80,
              "minLength": 1,
              "pattern": "^[a-z0-9][a-z0-9-]{0,79}$",
              "title": "Id",
              "type": "string"
            },
            "items": {
              "items": {
                "$ref": "#/$defs/SubqItem"
              },
              "maxItems": 50,
              "title": "Items",
              "type": "array"
            },
            "question": {
              "maxLength": 280,
              "minLength": 4,
              "title": "Question",
              "type": "string"
            },
            "theory_used": {
              "default": 0,
              "minimum": 0,
              "title": "Theory Used",
              "type": "integer"
            }
          },
          "required": [
            "id",
            "question",
            "coverage"
          ],
          "title": "Subquestion",
          "type": "object"
        }
      },
      "additionalProperties": false,
      "description": "A topic overview, resources page, outline state, or evidence card.",
      "properties": {
        "archives": {
          "anyOf": [
            {
              "items": {
                "pattern": "^vault/archives/[a-z0-9]+(?:-[a-z0-9]+)*/archive\\.md$",
                "type": "string"
              },
              "maxItems": 8,
              "minItems": 1,
              "type": "array"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "本卡引用的 Archive canonical paths；仅 kind: card；旧卡可省略",
          "title": "Archives"
        },
        "created": {
          "anyOf": [
            {
              "format": "date",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Created"
        },
        "history": {
          "anyOf": [
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "History"
        },
        "kind": {
          "description": "页面类型: overview 综合页 / resources 资源页 / outline 研究大纲 / card 圈外证据卡",
          "enum": [
            "overview",
            "resources",
            "outline",
            "card"
          ],
          "title": "Kind",
          "type": "string"
        },
        "subquestions": {
          "anyOf": [
            {
              "items": {
                "$ref": "#/$defs/Subquestion"
              },
              "maxItems": 6,
              "minItems": 1,
              "type": "array"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Subquestions"
        },
        "themes": {
          "anyOf": [
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "主题标签数组(复用全库 themes 词表);仅 kind: card",
          "title": "Themes"
        },
        "title": {
          "maxLength": 280,
          "minLength": 2,
          "title": "Title",
          "type": "string"
        },
        "type": {
          "const": "topic",
          "title": "Type",
          "type": "string"
        }
      },
      "required": [
        "type",
        "title",
        "kind"
      ],
      "title": "TopicSchema",
      "type": "object"
    }
  },
  "identity": {
    "fields": [
      "title",
      "kind"
    ],
    "properties": {
      "kind": {
        "description": "页面类型: overview 综合页 / resources 资源页 / outline 研究大纲 / card 圈外证据卡",
        "enum": [
          "overview",
          "resources",
          "outline",
          "card"
        ],
        "title": "Kind",
        "type": "string"
      },
      "title": {
        "maxLength": 280,
        "minLength": 2,
        "title": "Title",
        "type": "string"
      }
    },
    "required": [
      "title",
      "kind"
    ]
  },
  "path_pattern": "vault/topics/{slug}/{00-overview.md|01-resources.md|02-outline.md|cards/{card-slug}.md}",
  "schema_version": "quasi.artifact.topic/0.1"
};

export const ARCHIVE_ARTIFACT_CONTRACT = {
  "artifact_type": "archive",
  "collection": {
    "json_schema": {
      "$defs": {
        "ArchiveFile": {
          "additionalProperties": false,
          "properties": {
            "captured_at": {
              "format": "date-time",
              "title": "Captured At",
              "type": "string"
            },
            "media_type": {
              "minLength": 3,
              "title": "Media Type",
              "type": "string"
            },
            "path": {
              "pattern": "^originals/[a-z0-9]+(?:-[a-z0-9]+)*\\.[a-z0-9]+$",
              "title": "Path",
              "type": "string"
            },
            "sha256": {
              "pattern": "^[0-9a-f]{64}$",
              "title": "Sha256",
              "type": "string"
            },
            "size": {
              "exclusiveMinimum": 0,
              "title": "Size",
              "type": "integer"
            },
            "source": {
              "anyOf": [
                {
                  "$ref": "#/$defs/ArchiveSource"
                },
                {
                  "type": "null"
                }
              ],
              "default": null
            },
            "url": {
              "maxLength": 4096,
              "minLength": 8,
              "pattern": "^https?://",
              "title": "Url",
              "type": "string"
            }
          },
          "required": [
            "path",
            "media_type",
            "captured_at",
            "size",
            "sha256",
            "url"
          ],
          "title": "ArchiveFile",
          "type": "object"
        },
        "ArchiveSource": {
          "additionalProperties": false,
          "properties": {
            "title": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Title"
            },
            "url": {
              "maxLength": 4096,
              "minLength": 8,
              "pattern": "^https?://",
              "title": "Url",
              "type": "string"
            }
          },
          "required": [
            "url"
          ],
          "title": "ArchiveSource",
          "type": "object"
        }
      },
      "additionalProperties": false,
      "properties": {
        "coverage": {
          "default": "",
          "title": "Coverage",
          "type": "string"
        },
        "files": {
          "items": {
            "$ref": "#/$defs/ArchiveFile"
          },
          "title": "Files",
          "type": "array"
        },
        "schema_version": {
          "const": "quasi.archive.manifest/0.1",
          "default": "quasi.archive.manifest/0.1",
          "title": "Schema Version",
          "type": "string"
        },
        "source": {
          "$ref": "#/$defs/ArchiveSource"
        }
      },
      "required": [
        "source"
      ],
      "title": "ArchiveManifest",
      "type": "object"
    },
    "manifest": "manifest.yaml",
    "originals": "originals/",
    "source_inheritance": "files[].source overrides source; files[].url is the saved asset URL"
  },
  "document": {
    "additional_h2": false,
    "evidence_rules": [
      "一件 Archive 对应一件材料，kind 描述对象而非保存格式",
      "新建正文包含材料概况、来源与保存、内容与摘录；按下列栏目语义编撰，不能只给一句简介和附件列表。旧轻量记录仍可读取，不强制迁移或阻断收录",
      "frontmatter.source 是来源平台/机构，url 是材料直接链接，creator 是已核实作者或发布者；created 是建档日期，date 仅为已核实的原材料完整发布日期",
      "网页必须检查可见日期及页面元数据的发布日期证据；更新日期单独在来源与保存说明，不冒充发布日期。查无发布日期则省略 date 并说明未找到；部分日期只写正文，禁止用抓取时间、版权年份或评论日期补造",
      "manifest.yaml 记录共同出处与有序文件清单，单文件 source 仅覆盖例外；页面 url 与共同出处保持同一材料，不把 CDN 资源 URL 当材料来源",
      "原件缺失只在 coverage 和来源与保存说明；允许链接型空清单，不设完整率门槛",
      "明确已核读、仅保存/链接与未取得的范围；原文摘录、翻译、摘要和研究者判断分别标明，保留章节、步骤、图号或时间戳等可回查定位",
      "概述应让读者不打开每个原件也能理解对象、主要内容与适用范围；列出具体要点和重要限制，不用空泛评价代替内容",
      "原件由 helper 在本地原件栏目按相对 originals/ 路径陈列，无需逐文件分析或逐图标注；topics 合并保留已有成员"
    ],
    "h1": "使用 frontmatter.title；新建页面必须有 H1",
    "metadata_lines": [],
    "section_order": [
      "材料概况",
      "来源与保存",
      "内容与摘录",
      "关联",
      "本地原件"
    ],
    "sections": [
      {
        "description": "说明材料对象、作者/发布背景、用途、适用型号/版本或讨论语境；是原作、转载、截图还是节选。",
        "h2": "材料概况",
        "kind": "freeform",
        "required": false
      },
      {
        "description": "原标题和出处定位；发布日期的依据、单独的更新日期或未找到日期的说明；本次已核读/保存范围、缺失与语言/版本限制。保存时间见 manifest，不能与 created/date 混同。",
        "h2": "来源与保存",
        "kind": "freeform",
        "required": false
      },
      {
        "description": "用具体段落或要点归纳材料主旨、结构和关键信息（例如维修对象、方法、工具、接口/软件条件和限制），附来源定位；直接摘录按需，不编造逐字引文或未读音视频内容。",
        "h2": "内容与摘录",
        "kind": "freeform",
        "required": false
      },
      {
        "description": "有实质关联时链接 Topic、其他材料或笔记，并简述关系；无关联可省略。",
        "h2": "关联",
        "kind": "freeform",
        "required": false
      },
      {
        "description": "helper 追加的图片展示与其他原件链接，不要求逐一分析。",
        "h2": "本地原件",
        "kind": "freeform",
        "required": false
      }
    ]
  },
  "frontmatter": {
    "field_order": [
      "type",
      "title",
      "kind",
      "created",
      "creator",
      "date",
      "source",
      "url",
      "themes",
      "topics",
      "rating"
    ],
    "json_schema": {
      "additionalProperties": false,
      "properties": {
        "created": {
          "description": "本库建档日期，不是原文发布日期或快照时间",
          "format": "date",
          "title": "Created",
          "type": "string"
        },
        "creator": {
          "items": {
            "maxLength": 120,
            "minLength": 2,
            "type": "string"
          },
          "title": "Creator",
          "type": "array"
        },
        "date": {
          "anyOf": [
            {
              "format": "date",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "已核实的原材料完整发布日期；更新日期或部分日期写正文，未知省略",
          "title": "Date"
        },
        "kind": {
          "enum": [
            "patent",
            "thread",
            "post",
            "video",
            "image",
            "webpage",
            "document"
          ],
          "title": "Kind",
          "type": "string"
        },
        "rating": {
          "anyOf": [
            {
              "maximum": 5,
              "minimum": 1,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Rating"
        },
        "source": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "来源平台、发布机构或转存出处",
          "title": "Source"
        },
        "themes": {
          "items": {
            "type": "string"
          },
          "title": "Themes",
          "type": "array"
        },
        "title": {
          "maxLength": 280,
          "minLength": 2,
          "title": "Title",
          "type": "string"
        },
        "topics": {
          "items": {
            "type": "string"
          },
          "title": "Topics",
          "type": "array"
        },
        "type": {
          "const": "archive",
          "title": "Type",
          "type": "string"
        },
        "url": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "材料原始直接链接，与 manifest 共同出处对应",
          "title": "Url"
        }
      },
      "required": [
        "type",
        "title",
        "kind",
        "created"
      ],
      "title": "ArchiveSchema",
      "type": "object"
    }
  },
  "identity": {
    "fields": [
      "title",
      "kind",
      "url"
    ],
    "properties": {
      "kind": {
        "enum": [
          "patent",
          "thread",
          "post",
          "video",
          "image",
          "webpage",
          "document"
        ],
        "title": "Kind",
        "type": "string"
      },
      "title": {
        "maxLength": 280,
        "minLength": 2,
        "title": "Title",
        "type": "string"
      },
      "url": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "材料原始直接链接，与 manifest 共同出处对应",
        "title": "Url"
      }
    },
    "required": [
      "title",
      "kind"
    ]
  },
  "path_pattern": "vault/archives/{slug}/archive.md",
  "schema_version": "quasi.artifact.archive/0.2"
};

export const AUTHOR_ARTIFACT_CONTRACT = {
  "artifact_type": "author",
  "document": {
    "additional_h2": false,
    "evidence_rules": [
      "只使用 caller 提供并验证的 canonical Book/Paper corpus",
      "每份成员作品首次出现时使用由其 exact canonical path 推导的 wikilink",
      "保持原材料的证据类型，不虚构时间顺序、引文或作品关系",
      "rating 只能由 caller 提供的证据支持；没有证据时省略"
    ],
    "h1": "使用 frontmatter.name",
    "metadata_lines": [],
    "section_order": [
      "思想肖像",
      "代表著作",
      "学术轨迹",
      "关键概念",
      "理论网络",
      "金句要点",
      "项目关联"
    ],
    "sections": [
      {
        "description": "2-3 句概括该学者的核心关切和贡献",
        "h2": "思想肖像",
        "kind": "paragraph",
        "required": true
      },
      {
        "description": "仅列专著;没有专著的作者跳过",
        "h2": "代表著作",
        "kind": "paragraph",
        "required": false
      },
      {
        "description": "学者的研究历程",
        "h2": "学术轨迹",
        "kind": "paragraph",
        "required": true
      },
      {
        "description": "该学者提出/常用的核心概念表",
        "h2": "关键概念",
        "kind": "table",
        "required": true
      },
      {
        "description": "该学者对话过的思想家、理论传统",
        "h2": "理论网络",
        "kind": "bullet-list",
        "required": true
      },
      {
        "description": "可引用的代表性论点 / 原文金句",
        "h2": "金句要点",
        "kind": "blockquote-list",
        "required": true
      },
      {
        "child_kind": "paragraph",
        "description": "H3 per project — 项目名作为 H3 标签;reader 渲染为 tabs",
        "h2": "项目关联",
        "kind": "h3-project-tabs",
        "required": true
      }
    ]
  },
  "frontmatter": {
    "field_order": [
      "type",
      "name",
      "themes",
      "topics",
      "rating"
    ],
    "json_schema": {
      "additionalProperties": false,
      "description": "Profile of a scholar. One file per author.",
      "properties": {
        "name": {
          "description": "作者全名,作为该 entity 的展示名",
          "maxLength": 120,
          "minLength": 2,
          "title": "Name",
          "type": "string"
        },
        "rating": {
          "anyOf": [
            {
              "maximum": 5,
              "minimum": 1,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "整体学术评分(1..5,reader 渲染为 ★);可选",
          "title": "Rating"
        },
        "themes": {
          "description": "研究方向标签数组;允许空但 lint warn '0 themes 可能漏写'",
          "items": {
            "type": "string"
          },
          "title": "Themes",
          "type": "array"
        },
        "topics": {
          "description": "所属 topic 语料的 slug 数组;供前端按成员反查;允许空",
          "items": {
            "type": "string"
          },
          "title": "Topics",
          "type": "array"
        },
        "type": {
          "const": "author",
          "description": "类型判别符,固定为字面量 'author'",
          "title": "Type",
          "type": "string"
        }
      },
      "required": [
        "type",
        "name"
      ],
      "title": "AuthorSchema",
      "type": "object"
    }
  },
  "identity": {
    "fields": [
      "name"
    ],
    "properties": {
      "name": {
        "description": "作者全名,作为该 entity 的展示名",
        "maxLength": 120,
        "minLength": 2,
        "title": "Name",
        "type": "string"
      }
    },
    "required": [
      "name"
    ]
  },
  "path_pattern": "vault/authors/{slug}.md",
  "schema_version": "quasi.artifact.author/0.1"
};

export const PAPER_ARTIFACT_CONTRACT = {
  "artifact_type": "paper",
  "document": {
    "additional_h2": false,
    "evidence_rules": [],
    "h1": "忠实概括论文标题；不添加装饰性或项目式后缀",
    "metadata_lines": [
      "英文原标题",
      "作者",
      "期刊来源",
      "仅在 identity 提供 DOI 时写 DOI"
    ],
    "section_order": [
      "核心论点",
      "理论框架",
      "分节摘要",
      "关键概念",
      "核心引用",
      "金句要点",
      "项目关联"
    ],
    "sections": [
      {
        "description": "说明研究问题、中心论点、证据、推理、贡献，以及正文实际提出的限制",
        "h2": "核心论点",
        "kind": "paragraph",
        "required": true
      },
      {
        "description": "理论传统、对话学者和思想资源",
        "h2": "理论框架",
        "kind": "paragraph",
        "required": true
      },
      {
        "child_kind": "paragraph",
        "description": "按原文小节结构 — H3 是原文 sub-section 标题",
        "h2": "分节摘要",
        "kind": "h3-sections",
        "required": true
      },
      {
        "columns": [
          "概念",
          "英文",
          "提出者",
          "定义"
        ],
        "description": "论文中讨论的核心概念(同名 H2,paper 用 table)",
        "h2": "关键概念",
        "kind": "table",
        "recommended_items": {
          "max": 5,
          "min": 3
        },
        "required": true
      },
      {
        "description": "论文实质使用的著作及其在论证中的作用；不补写 input 无法支持的书目信息",
        "h2": "核心引用",
        "kind": "numbered-list",
        "recommended_items": {
          "max": 15,
          "min": 5
        },
        "required": true
      },
      {
        "condition": "只有 input 中存在可定位的准确引文时才生成",
        "description": "可引用段落 / 原文金句",
        "h2": "金句要点",
        "kind": "blockquote-list",
        "required": false
      },
      {
        "child_kind": "numbered-list",
        "condition": "只有 caller identity 明确提供项目语境时才生成",
        "description": "",
        "h2": "项目关联",
        "kind": "h3-project-tabs",
        "required": false
      }
    ]
  },
  "frontmatter": {
    "field_order": [
      "type",
      "title",
      "authors",
      "year",
      "journal",
      "themes",
      "doi",
      "topics",
      "rating"
    ],
    "json_schema": {
      "additionalProperties": false,
      "description": "A journal article analysis.",
      "properties": {
        "authors": {
          "description": "作者数组,永远 ≥1 元素",
          "items": {
            "maxLength": 120,
            "minLength": 2,
            "type": "string"
          },
          "minItems": 1,
          "title": "Authors",
          "type": "array"
        },
        "doi": {
          "anyOf": [
            {
              "pattern": "^10\\.\\d+/.+",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Doi"
        },
        "journal": {
          "description": "期刊名;paper = 期刊论文,必填",
          "maxLength": 200,
          "minLength": 2,
          "title": "Journal",
          "type": "string"
        },
        "rating": {
          "anyOf": [
            {
              "maximum": 5,
              "minimum": 1,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Rating"
        },
        "themes": {
          "description": "主题标签数组;paper 必须有主题(不允许空 — 与 chapter 不同)",
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "title": "Themes",
          "type": "array"
        },
        "title": {
          "maxLength": 280,
          "minLength": 2,
          "title": "Title",
          "type": "string"
        },
        "topics": {
          "description": "所属 topic 语料的 slug 数组;供前端按成员反查;允许空",
          "items": {
            "type": "string"
          },
          "title": "Topics",
          "type": "array"
        },
        "type": {
          "const": "paper",
          "title": "Type",
          "type": "string"
        },
        "year": {
          "anyOf": [
            {
              "maximum": 2030,
              "minimum": 1500,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "description": "发表年",
          "title": "Year"
        }
      },
      "required": [
        "type",
        "title",
        "authors",
        "year",
        "journal",
        "themes"
      ],
      "title": "PaperSchema",
      "type": "object"
    }
  },
  "identity": {
    "fields": [
      "title",
      "authors",
      "year",
      "journal",
      "doi"
    ],
    "properties": {
      "authors": {
        "description": "作者数组,永远 ≥1 元素",
        "items": {
          "maxLength": 120,
          "minLength": 2,
          "type": "string"
        },
        "minItems": 1,
        "title": "Authors",
        "type": "array"
      },
      "doi": {
        "anyOf": [
          {
            "pattern": "^10\\.\\d+/.+",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Doi"
      },
      "journal": {
        "description": "期刊名;paper = 期刊论文,必填",
        "maxLength": 200,
        "minLength": 2,
        "title": "Journal",
        "type": "string"
      },
      "title": {
        "maxLength": 280,
        "minLength": 2,
        "title": "Title",
        "type": "string"
      },
      "year": {
        "anyOf": [
          {
            "maximum": 2030,
            "minimum": 1500,
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "description": "发表年",
        "title": "Year"
      }
    },
    "required": [
      "title",
      "authors",
      "year",
      "journal"
    ]
  },
  "path_pattern": "vault/papers/{slug}.md",
  "schema_version": "quasi.artifact.paper/0.1"
};

export const CHAPTER_ARTIFACT_CONTRACT = {
  "artifact_type": "chapter",
  "document": {
    "additional_h2": false,
    "evidence_rules": [],
    "h1": "忠实呈现 caller identity 中的 chapter title；chapter label 非 null 时保留其前缀，不添加装饰性后缀",
    "metadata_lines": [
      "可写原文标题、作者和关键词；每一项必须由 input 或 caller identity 支持"
    ],
    "section_order": [
      "核心论点",
      "理论框架",
      "分节摘要",
      "关键概念",
      "核心引用",
      "金句要点",
      "项目关联"
    ],
    "sections": [
      {
        "description": "章节的中心论点和论证逻辑",
        "h2": "核心论点",
        "kind": "paragraph",
        "required": true
      },
      {
        "description": "理论传统、对话学者和思想资源",
        "h2": "理论框架",
        "kind": "paragraph",
        "required": true
      },
      {
        "child_kind": "paragraph",
        "description": "按原文小节结构 — H3 是原文 sub-section 标题",
        "h2": "分节摘要",
        "kind": "h3-sections",
        "required": true
      },
      {
        "columns": [
          "概念",
          "英文",
          "提出者",
          "定义"
        ],
        "description": "章节中讨论的核心概念(同名 H2,chapter 用 table)",
        "h2": "关键概念",
        "kind": "table",
        "recommended_items": {
          "max": 5,
          "min": 3
        },
        "required": true
      },
      {
        "description": "本章实质使用的著作及其在论证中的作用；不补写 input 无法支持的书目信息",
        "h2": "核心引用",
        "kind": "numbered-list",
        "recommended_items": {
          "max": 15,
          "min": 5
        },
        "required": true
      },
      {
        "condition": "只有 input 中存在可定位的准确引文时才生成",
        "description": "可引用段落 / 原文金句",
        "h2": "金句要点",
        "kind": "blockquote-list",
        "required": false
      },
      {
        "child_kind": "numbered-list",
        "condition": "只有 caller identity 明确提供项目语境时才生成",
        "description": "",
        "h2": "项目关联",
        "kind": "h3-project-tabs",
        "required": false
      }
    ]
  },
  "frontmatter": {
    "field_order": [
      "type",
      "title",
      "authors",
      "year",
      "book",
      "themes",
      "topics",
      "rating"
    ],
    "json_schema": {
      "additionalProperties": false,
      "description": "A chapter analysis. Must live under vault/books/<slug>/.",
      "properties": {
        "authors": {
          "description": "章作者;编纂本里可与父书 authors 不同(章节作者 != 书编者)",
          "items": {
            "maxLength": 120,
            "minLength": 2,
            "type": "string"
          },
          "minItems": 1,
          "title": "Authors",
          "type": "array"
        },
        "book": {
          "description": "父书 slug(从文件路径派生,如 'allison-nightwork-1994');vault-wide lint 校验该 slug 真的存在对应的 book 文件",
          "maxLength": 200,
          "minLength": 2,
          "title": "Book",
          "type": "string"
        },
        "rating": {
          "anyOf": [
            {
              "maximum": 5,
              "minimum": 1,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Rating"
        },
        "themes": {
          "description": "章节级主题;允许空(章节经常没有独立主题标签)",
          "items": {
            "type": "string"
          },
          "title": "Themes",
          "type": "array"
        },
        "title": {
          "description": "章节展示标题;caller 提供 chapter label 时以其为前缀,未提供时忠实保留 manifest title",
          "maxLength": 280,
          "minLength": 2,
          "title": "Title",
          "type": "string"
        },
        "topics": {
          "description": "所属 topic 语料的 slug 数组;供前端按成员反查;允许空",
          "items": {
            "type": "string"
          },
          "title": "Topics",
          "type": "array"
        },
        "type": {
          "const": "chapter",
          "title": "Type",
          "type": "string"
        },
        "year": {
          "anyOf": [
            {
              "maximum": 2030,
              "minimum": 1500,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "description": "通常等于父书 year",
          "title": "Year"
        }
      },
      "required": [
        "type",
        "title",
        "authors",
        "year",
        "book"
      ],
      "title": "ChapterSchema",
      "type": "object"
    }
  },
  "identity": {
    "fields": [
      "title",
      "authors",
      "year",
      "book"
    ],
    "properties": {
      "authors": {
        "description": "章作者;编纂本里可与父书 authors 不同(章节作者 != 书编者)",
        "items": {
          "maxLength": 120,
          "minLength": 2,
          "type": "string"
        },
        "minItems": 1,
        "title": "Authors",
        "type": "array"
      },
      "book": {
        "description": "父书 slug(从文件路径派生,如 'allison-nightwork-1994');vault-wide lint 校验该 slug 真的存在对应的 book 文件",
        "maxLength": 200,
        "minLength": 2,
        "title": "Book",
        "type": "string"
      },
      "title": {
        "description": "章节展示标题;caller 提供 chapter label 时以其为前缀,未提供时忠实保留 manifest title",
        "maxLength": 280,
        "minLength": 2,
        "title": "Title",
        "type": "string"
      },
      "year": {
        "anyOf": [
          {
            "maximum": 2030,
            "minimum": 1500,
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "description": "通常等于父书 year",
        "title": "Year"
      }
    },
    "required": [
      "title",
      "authors",
      "year",
      "book"
    ]
  },
  "path_pattern": "vault/books/{book_slug}/ch{slot}-{chapter_slug}.md",
  "schema_version": "quasi.artifact.chapter/0.1"
};

export const BOOK_ARTIFACT_CONTRACT = {
  "artifact_type": "book",
  "document": {
    "additional_h2": false,
    "evidence_rules": [],
    "h1": "使用 frontmatter.title；不添加模板式或项目式后缀",
    "metadata_lines": [],
    "section_order": [
      "核心论点",
      "章节逻辑",
      "关键概念",
      "理论贡献",
      "精读章节",
      "项目关联"
    ],
    "sections": [
      {
        "description": "综合全部 supplied chapter analyses，说明全书的中心主题、核心论证和证据关系",
        "h2": "核心论点",
        "kind": "paragraph",
        "required": true
      },
      {
        "description": "各章如何构成整体论证;章节间递进/对话/互补关系",
        "h2": "章节逻辑",
        "kind": "paragraph",
        "required": true
      },
      {
        "columns": [
          "概念",
          "英文",
          "提出者",
          "定义"
        ],
        "description": "全书的核心概念表(同名 H2,book 用 table 形态)",
        "h2": "关键概念",
        "kind": "table",
        "required": true
      },
      {
        "description": "本书对学术领域的整体贡献",
        "h2": "理论贡献",
        "kind": "paragraph",
        "required": true
      },
      {
        "condition": "只推荐 supplied chapter analyses 中实际存在的章节",
        "description": "按优先级排序的推荐精读章节",
        "h2": "精读章节",
        "kind": "numbered-list",
        "required": true
      },
      {
        "child_kind": "paragraph",
        "condition": "只有 caller identity 明确提供项目语境时才生成",
        "description": "",
        "h2": "项目关联",
        "kind": "h3-project-tabs",
        "required": false
      }
    ]
  },
  "frontmatter": {
    "field_order": [
      "type",
      "title",
      "authors",
      "year",
      "publisher",
      "isbn",
      "doi",
      "category",
      "themes",
      "topics",
      "rating"
    ],
    "json_schema": {
      "additionalProperties": false,
      "description": "Analytical overview of a book. Aligns with BibTeX @book / @collection.",
      "properties": {
        "authors": {
          "description": "作者或编者数组;角色由 category 区分;永远数组(单作者也包成 1 元素)",
          "items": {
            "maxLength": 120,
            "minLength": 2,
            "type": "string"
          },
          "minItems": 1,
          "title": "Authors",
          "type": "array"
        },
        "category": {
          "default": "monograph",
          "description": "书籍类别;BibTeX export 时驱动 @book vs @collection + author vs editor",
          "enum": [
            "monograph",
            "edited-volume",
            "handbook",
            "other"
          ],
          "title": "Category",
          "type": "string"
        },
        "doi": {
          "anyOf": [
            {
              "pattern": "^10\\.\\d+/.+",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Doi"
        },
        "isbn": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "ISBN;接受 int|str,coerce 为 str;格式校验留给 lint",
          "title": "Isbn"
        },
        "publisher": {
          "description": "出版社;Phase 1 lint warn,Phase 2 严格必填",
          "maxLength": 200,
          "minLength": 2,
          "title": "Publisher",
          "type": "string"
        },
        "rating": {
          "anyOf": [
            {
              "maximum": 5,
              "minimum": 1,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Rating"
        },
        "themes": {
          "description": "主题标签数组",
          "items": {
            "type": "string"
          },
          "title": "Themes",
          "type": "array"
        },
        "title": {
          "description": "书名(含副标题)",
          "maxLength": 280,
          "minLength": 2,
          "title": "Title",
          "type": "string"
        },
        "topics": {
          "description": "所属 topic 语料的 slug 数组;供前端按成员反查;允许空",
          "items": {
            "type": "string"
          },
          "title": "Topics",
          "type": "array"
        },
        "type": {
          "const": "book",
          "title": "Type",
          "type": "string"
        },
        "year": {
          "anyOf": [
            {
              "maximum": 2030,
              "minimum": 1500,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "description": "出版年",
          "title": "Year"
        }
      },
      "required": [
        "type",
        "title",
        "authors",
        "year",
        "publisher"
      ],
      "title": "BookSchema",
      "type": "object"
    }
  },
  "identity": {
    "fields": [
      "title",
      "authors",
      "year",
      "publisher",
      "isbn",
      "category"
    ],
    "properties": {
      "authors": {
        "description": "作者或编者数组;角色由 category 区分;永远数组(单作者也包成 1 元素)",
        "items": {
          "maxLength": 120,
          "minLength": 2,
          "type": "string"
        },
        "minItems": 1,
        "title": "Authors",
        "type": "array"
      },
      "category": {
        "default": "monograph",
        "description": "书籍类别;BibTeX export 时驱动 @book vs @collection + author vs editor",
        "enum": [
          "monograph",
          "edited-volume",
          "handbook",
          "other"
        ],
        "title": "Category",
        "type": "string"
      },
      "isbn": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "ISBN;接受 int|str,coerce 为 str;格式校验留给 lint",
        "title": "Isbn"
      },
      "publisher": {
        "description": "出版社;Phase 1 lint warn,Phase 2 严格必填",
        "maxLength": 200,
        "minLength": 2,
        "title": "Publisher",
        "type": "string"
      },
      "title": {
        "description": "书名(含副标题)",
        "maxLength": 280,
        "minLength": 2,
        "title": "Title",
        "type": "string"
      },
      "year": {
        "anyOf": [
          {
            "maximum": 2030,
            "minimum": 1500,
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "description": "出版年",
        "title": "Year"
      }
    },
    "required": [
      "title",
      "authors",
      "year",
      "publisher"
    ]
  },
  "path_pattern": "vault/books/{slug}/00-overview.md",
  "schema_version": "quasi.artifact.book/0.1"
};

export const TALK_ARTIFACT_CONTRACT = {
  "artifact_type": "talk",
  "document": {
    "additional_h2": false,
    "evidence_rules": [],
    "h1": "使用 frontmatter.title",
    "metadata_lines": [
      "讲者",
      "日期",
      "场合",
      "时长",
      "transcript 未说明的非必填展示项标为（未说明）"
    ],
    "section_order": [
      "核心论点",
      "分节摘要",
      "关键概念",
      "项目关联",
      "文献人物",
      "时间脉络"
    ],
    "sections": [
      {
        "description": "这场讲座的中心主张、问题意识、贡献(2-4 段)",
        "h2": "核心论点",
        "kind": "paragraph",
        "required": true
      },
      {
        "child_kind": "paragraph",
        "description": "按内容实质分节(H3 小标题);摘要主体;问答并入此处;live talk 的每个 H3 下首行严格为「时间：`[mm:ss]`–`[mm:ss]`」,起止点逐项对照 transcript evidence 的实际发言范围核定,反引号必须按字面保留;超过一小时用 `[h:mm:ss]`",
        "h2": "分节摘要",
        "kind": "h3-sections",
        "required": true
      },
      {
        "columns": [
          "概念",
          "英文",
          "定义"
        ],
        "description": "讲座提出/反复使用的核心概念表;无则保留表头写一行",
        "h2": "关键概念",
        "kind": "table",
        "required": true
      },
      {
        "description": "与 vault/authors、BTS 综述议题、同系列讲座的关联;无则写「（暂无)」",
        "h2": "项目关联",
        "kind": "bullet-list",
        "required": true
      },
      {
        "description": "讲座点到的学者、著作、概念来源(列表);无则写一行说明",
        "h2": "文献人物",
        "kind": "bullet-list",
        "required": true
      },
      {
        "description": "详尽视频时间索引(talk 专属,置末,粒度细于分节摘要,不得用分节起止范围替代);每行严格为「- `[mm:ss]` 主题 — 概括」,时间戳取自 transcript,反引号必须按字面保留在输出里(播放器定位依赖它);超过一小时用 `[h:mm:ss]`",
        "h2": "时间脉络",
        "kind": "bullet-list",
        "required": true
      }
    ]
  },
  "frontmatter": {
    "field_order": [
      "type",
      "title",
      "date",
      "speaker",
      "themes",
      "rating",
      "media"
    ],
    "json_schema": {
      "additionalProperties": false,
      "description": "A talk / lecture recording analysis.",
      "properties": {
        "date": {
          "description": "录制日期(整日 ISO,如 2024-11-08)",
          "format": "date",
          "title": "Date",
          "type": "string"
        },
        "media": {
          "description": "媒体文件名,如 recording.mov(gitignore)",
          "maxLength": 200,
          "minLength": 2,
          "title": "Media",
          "type": "string"
        },
        "rating": {
          "anyOf": [
            {
              "maximum": 5,
              "minimum": 1,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Rating"
        },
        "speaker": {
          "description": "讲者姓名数组(可关联 vault/authors/);抽不到留空(省略整键)",
          "items": {
            "maxLength": 120,
            "minLength": 2,
            "type": "string"
          },
          "title": "Speaker",
          "type": "array"
        },
        "themes": {
          "description": "主题标签数组(复用全库 themes 词表);静音/失败录制可空",
          "items": {
            "type": "string"
          },
          "title": "Themes",
          "type": "array"
        },
        "title": {
          "maxLength": 280,
          "minLength": 2,
          "title": "Title",
          "type": "string"
        },
        "type": {
          "const": "talk",
          "title": "Type",
          "type": "string"
        }
      },
      "required": [
        "type",
        "title",
        "date",
        "media"
      ],
      "title": "TalkSchema",
      "type": "object"
    }
  },
  "identity": {
    "fields": [
      "title",
      "date",
      "media"
    ],
    "properties": {
      "date": {
        "description": "录制日期(整日 ISO,如 2024-11-08)",
        "format": "date",
        "title": "Date",
        "type": "string"
      },
      "media": {
        "description": "媒体文件名,如 recording.mov(gitignore)",
        "maxLength": 200,
        "minLength": 2,
        "title": "Media",
        "type": "string"
      },
      "title": {
        "maxLength": 280,
        "minLength": 2,
        "title": "Title",
        "type": "string"
      }
    },
    "required": [
      "title",
      "date",
      "media"
    ]
  },
  "path_pattern": "vault/talks/{slug}/talk.md",
  "schema_version": "quasi.artifact.talk/0.1"
};

export const WEBPAGE_ARTIFACT_CONTRACT = {
  "artifact_type": "webpage",
  "document": {
    "additional_h2": false,
    "evidence_rules": [],
    "h1": "使用 frontmatter.title",
    "metadata_lines": [],
    "section_order": [
      "Summary",
      "Content"
    ],
    "sections": [
      {
        "description": "简要说明页面内容、论点及其知识库价值",
        "h2": "Summary",
        "kind": "paragraph",
        "required": true
      },
      {
        "description": "逐字保留 source.md 的完整清洗后正文；内部标题从 H3 开始",
        "h2": "Content",
        "kind": "freeform",
        "required": true
      }
    ]
  },
  "frontmatter": {
    "field_order": [
      "type",
      "title",
      "url",
      "captured_at",
      "authors",
      "published",
      "site",
      "themes",
      "topics",
      "rating"
    ],
    "json_schema": {
      "additionalProperties": false,
      "description": "The semantic metadata for one captured webpage.",
      "properties": {
        "authors": {
          "items": {
            "maxLength": 120,
            "minLength": 2,
            "type": "string"
          },
          "title": "Authors",
          "type": "array"
        },
        "captured_at": {
          "format": "date-time",
          "title": "Captured At",
          "type": "string"
        },
        "published": {
          "anyOf": [
            {
              "format": "date",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Published"
        },
        "rating": {
          "anyOf": [
            {
              "maximum": 5,
              "minimum": 1,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Rating"
        },
        "site": {
          "anyOf": [
            {
              "maxLength": 200,
              "minLength": 2,
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Site"
        },
        "themes": {
          "items": {
            "type": "string"
          },
          "title": "Themes",
          "type": "array"
        },
        "title": {
          "maxLength": 280,
          "minLength": 2,
          "title": "Title",
          "type": "string"
        },
        "topics": {
          "items": {
            "type": "string"
          },
          "title": "Topics",
          "type": "array"
        },
        "type": {
          "const": "webpage",
          "title": "Type",
          "type": "string"
        },
        "url": {
          "maxLength": 2048,
          "minLength": 8,
          "title": "Url",
          "type": "string"
        }
      },
      "required": [
        "type",
        "title",
        "url",
        "captured_at"
      ],
      "title": "WebpageSchema",
      "type": "object"
    }
  },
  "identity": {
    "fields": [
      "title",
      "url",
      "site"
    ],
    "properties": {
      "site": {
        "anyOf": [
          {
            "maxLength": 200,
            "minLength": 2,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Site"
      },
      "title": {
        "maxLength": 280,
        "minLength": 2,
        "title": "Title",
        "type": "string"
      },
      "url": {
        "maxLength": 2048,
        "minLength": 8,
        "title": "Url",
        "type": "string"
      }
    },
    "required": [
      "title",
      "url"
    ]
  },
  "path_pattern": "vault/webpages/{slug}/webpage.md",
  "schema_version": "quasi.artifact.webpage/0.1"
};

export const TOPIC_OUTLINE_SUBQUESTIONS_SCHEMA = {
  "items": {
    "additionalProperties": false,
    "description": "研究大纲里的一个子问题(仅 kind: outline 页携带)。",
    "properties": {
      "cards": {
        "description": "证据卡 slug 表(cards/{slug}.md),与 items 平行的圈外证据通道",
        "items": {
          "maxLength": 80,
          "minLength": 2,
          "pattern": "^[a-z0-9][a-z0-9-]*$",
          "type": "string"
        },
        "maxItems": 50,
        "type": "array"
      },
      "channel": {
        "enum": [
          "academic",
          "web",
          "mixed"
        ],
        "type": "string"
      },
      "coverage": {
        "enum": [
          "gap",
          "thin",
          "covered",
          "saturated"
        ],
        "type": "string"
      },
      "id": {
        "maxLength": 80,
        "minLength": 1,
        "pattern": "^[a-z0-9][a-z0-9-]{0,79}$",
        "type": "string"
      },
      "items": {
        "items": {
          "additionalProperties": false,
          "description": "子问题的一个学术语料成员(持久在 outline frontmatter,跨轮跨重跑累计)。\n\n只收 vault 分析件(book/paper/talk)。圈外证据卡走 `Subquestion.cards`\n独立通道 —— 卡不是分析件,混进来会让 synth 按分析件路径去读一个不存在的产物。",
          "properties": {
            "kind": {
              "enum": [
                "book",
                "paper",
                "talk"
              ],
              "type": "string"
            },
            "role": {
              "anyOf": [
                {
                  "enum": [
                    "evidence",
                    "theory",
                    "method",
                    "context"
                  ],
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ]
            },
            "slug": {
              "maxLength": 80,
              "minLength": 1,
              "pattern": "^[a-z0-9][a-z0-9-]{0,79}$",
              "type": "string"
            }
          },
          "required": [
            "kind",
            "slug",
            "role"
          ],
          "type": "object"
        },
        "maxItems": 50,
        "type": "array"
      },
      "question": {
        "maxLength": 280,
        "minLength": 4,
        "type": "string"
      },
      "theory_used": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "id",
      "question",
      "coverage",
      "channel",
      "theory_used",
      "items",
      "cards"
    ],
    "type": "object"
  },
  "maxItems": 6,
  "minItems": 1,
  "type": "array"
};

export const OPERATION_CATALOG = {
  "archive.identify": {
    "kinds": [
      "archive"
    ],
    "phase": "Search",
    "effect": "readonly",
    "agent": "quasi:archive-agent",
    "artifacts": {}
  },
  "archive.collect": {
    "kinds": [
      "archive"
    ],
    "phase": "Acquire",
    "effect": "writer",
    "agent": "quasi:archive-agent",
    "artifacts": {
      "output": "vault/archives/{slug}/archive.md",
      "manifest": "vault/archives/{slug}/manifest.yaml",
      "originals": "vault/archives/{slug}/originals"
    }
  },
  "archive.audit": {
    "kinds": [
      "archive"
    ],
    "phase": "Audit",
    "effect": "writer",
    "agent": "quasi:audit-agent",
    "artifacts": {
      "target": "vault/archives/{slug}/archive.md"
    }
  },
  "topic.discover-archives": {
    "kinds": [
      "topic"
    ],
    "phase": "Search",
    "effect": "readonly",
    "agent": "quasi:webcard-agent",
    "artifacts": {}
  },
  "webpage.identify": {
    "kinds": [
      "webpage"
    ],
    "phase": "Search",
    "effect": "readonly",
    "agent": "quasi:webpage-agent",
    "artifacts": {}
  },
  "webpage.capture": {
    "kinds": [
      "webpage"
    ],
    "phase": "Acquire",
    "effect": "writer",
    "agent": "quasi:webpage-agent",
    "artifacts": {
      "snapshot": "vault/webpages/{slug}/snapshot.webarchive"
    }
  },
  "webpage.prepare": {
    "kinds": [
      "webpage"
    ],
    "phase": "Prepare",
    "effect": "writer",
    "agent": "quasi:webpage-agent",
    "artifacts": {
      "snapshot": "vault/webpages/{slug}/snapshot.webarchive",
      "output": "processing/webpages/{slug}/source.md"
    }
  },
  "webpage.analyse": {
    "kinds": [
      "webpage"
    ],
    "phase": "Analyse",
    "effect": "writer",
    "agent": "quasi:analyse-agent",
    "artifacts": {
      "output": "vault/webpages/{slug}/webpage.md"
    }
  },
  "webpage.audit": {
    "kinds": [
      "webpage"
    ],
    "phase": "Audit",
    "effect": "writer",
    "agent": "quasi:audit-agent",
    "artifacts": {
      "target": "vault/webpages/{slug}/webpage.md"
    }
  },
  "material.search": {
    "kinds": [
      "paper",
      "book"
    ],
    "phase": "Search",
    "effect": "readonly",
    "agent": "quasi:metadata-agent",
    "artifacts": {}
  },
  "paper.acquire": {
    "kinds": [
      "paper"
    ],
    "phase": "Acquire",
    "effect": "writer",
    "agent": "quasi:download-agent",
    "artifacts": {
      "outputPdf": "sources/{slug}.pdf",
      "outputText": "sources/{slug}.txt"
    }
  },
  "paper.prepare": {
    "kinds": [
      "paper"
    ],
    "phase": "Prepare",
    "effect": "writer",
    "agent": "quasi:extract-agent",
    "artifacts": {
      "input": "{input}",
      "sourcePdf": "sources/{slug}.pdf",
      "sourceText": "sources/{slug}.txt",
      "normalized": "processing/papers/{slug}/source.txt",
      "legacyRecoverySource": "processing/papers/{slug}/ocr.pdf",
      "legacyRecoveryText": "processing/papers/{slug}/ocr.txt"
    }
  },
  "paper.ocr": {
    "kinds": [
      "paper"
    ],
    "phase": "Prepare",
    "effect": "writer",
    "agent": "quasi:extract-agent",
    "artifacts": {
      "source": "sources/{slug}.pdf",
      "lock": "processing/papers/{slug}/.ocr-generation.lock",
      "workDir": "processing/papers/{slug}/.ocr-work/{generationKey}",
      "progress": "processing/papers/{slug}/.ocr-work/{generationKey}/ocr.progress.json",
      "generationDir": "processing/papers/{slug}/ocr-generations/{generationKey}",
      "recoveryPdf": "processing/papers/{slug}/ocr-generations/{generationKey}/ocr.pdf",
      "recoveryText": "processing/papers/{slug}/ocr-generations/{generationKey}/ocr.txt",
      "manifest": "processing/papers/{slug}/ocr-generations/{generationKey}/manifest.json"
    }
  },
  "paper.analyse": {
    "kinds": [
      "paper"
    ],
    "phase": "Analyse",
    "effect": "writer",
    "agent": "quasi:analyse-agent",
    "artifacts": {
      "output": "vault/papers/{slug}.md"
    }
  },
  "paper.audit": {
    "kinds": [
      "paper"
    ],
    "phase": "Audit",
    "effect": "writer",
    "agent": "quasi:audit-agent",
    "artifacts": {
      "target": "vault/papers/{slug}.md"
    }
  },
  "book.acquire": {
    "kinds": [
      "book"
    ],
    "phase": "Acquire",
    "effect": "writer",
    "agent": "quasi:download-agent",
    "artifacts": {}
  },
  "book.prepare": {
    "kinds": [
      "book"
    ],
    "phase": "Prepare",
    "effect": "writer",
    "agent": "quasi:extract-agent",
    "artifacts": {
      "input": "{input}",
      "source": "sources/{slug}.{format}",
      "normalized": "processing/chapters/{slug}/source.txt",
      "recoverySource": "processing/chapters/{slug}/ocr.pdf",
      "ocrProgress": "processing/chapters/{slug}/ocr.progress.json",
      "recoveryText": "processing/chapters/{slug}/ocr.txt",
      "outputDir": "processing/chapters/{slug}",
      "manifest": "processing/chapters/{slug}/manifest.json"
    }
  },
  "book.ocr": {
    "kinds": [
      "book"
    ],
    "phase": "Prepare",
    "effect": "writer",
    "agent": "quasi:extract-agent",
    "artifacts": {
      "source": "sources/{slug}.pdf",
      "lock": "processing/chapters/{slug}/.ocr-generation.lock",
      "workDir": "processing/chapters/{slug}/.ocr-work/{generationKey}",
      "progress": "processing/chapters/{slug}/.ocr-work/{generationKey}/ocr.progress.json",
      "generationDir": "processing/chapters/{slug}/ocr-generations/{generationKey}",
      "recoveryPdf": "processing/chapters/{slug}/ocr-generations/{generationKey}/ocr.pdf",
      "recoveryText": "processing/chapters/{slug}/ocr-generations/{generationKey}/ocr.txt",
      "manifest": "processing/chapters/{slug}/ocr-generations/{generationKey}/manifest.json"
    }
  },
  "chapter.analyse": {
    "kinds": [
      "book"
    ],
    "phase": "Analyse",
    "effect": "writer",
    "agent": "quasi:analyse-agent",
    "artifacts": {}
  },
  "book.synthesise": {
    "kinds": [
      "book"
    ],
    "phase": "Synthesise",
    "effect": "writer",
    "agent": "quasi:synthesis-agent",
    "artifacts": {
      "output": "vault/books/{slug}/00-overview.md"
    }
  },
  "book.audit": {
    "kinds": [
      "book"
    ],
    "phase": "Audit",
    "effect": "writer",
    "agent": "quasi:audit-agent",
    "artifacts": {
      "target": "vault/books/{slug}"
    }
  },
  "talk.prepare": {
    "kinds": [
      "talk"
    ],
    "phase": "Prepare",
    "effect": "writer",
    "agent": "quasi:transcribe-agent",
    "artifacts": {
      "processingDir": "processing/talks/{slug}",
      "manifest": "processing/talks/{slug}/manifest.json",
      "prepared": "vault/talks/{slug}/recording.mp4",
      "transcript": "vault/talks/{slug}/transcript.md",
      "subtitle": "vault/talks/{slug}/recording.srt",
      "canonical": "vault/talks/{slug}/talk.md"
    }
  },
  "talk.analyse": {
    "kinds": [
      "talk"
    ],
    "phase": "Analyse",
    "effect": "writer",
    "agent": "quasi:analyse-agent",
    "artifacts": {
      "output": "vault/talks/{slug}/talk.md"
    }
  },
  "talk.audit": {
    "kinds": [
      "talk"
    ],
    "phase": "Audit",
    "effect": "writer",
    "agent": "quasi:audit-agent",
    "artifacts": {
      "target": "vault/talks/{slug}/talk.md"
    }
  },
  "translation.prepare": {
    "kinds": [
      "translation"
    ],
    "phase": "Prepare",
    "effect": "writer",
    "agent": "quasi:translate-agent",
    "artifacts": {
      "source": "sources/{slug}.pdf",
      "derivatives": "processing/translations/{slug}-*.pdf",
      "output": "processing/translations/{slug}-{target}.pdf",
      "manifest": "processing/translations/{slug}-{target}.manifest.json",
      "recoverySource": "processing/translations/{slug}-{target}-reocr.pdf"
    }
  },
  "topic.recall": {
    "kinds": [
      "topic"
    ],
    "phase": "Recall",
    "effect": "readonly",
    "agent": "general-purpose",
    "artifacts": {}
  },
  "topic.steer": {
    "kinds": [
      "topic"
    ],
    "phase": "Search",
    "effect": "writer",
    "agent": "quasi:steer-agent",
    "artifacts": {
      "outputPath": "vault/topics/{slug}/02-outline.md"
    }
  },
  "topic.webcard": {
    "kinds": [
      "topic"
    ],
    "phase": "Search",
    "effect": "writer",
    "agent": "quasi:webcard-agent",
    "artifacts": {
      "cardPath": "vault/topics/{slug}/cards/{target}.md"
    }
  },
  "topic.synthesise.overview": {
    "kinds": [
      "topic"
    ],
    "phase": "Synthesise",
    "effect": "writer",
    "agent": "quasi:synthesis-agent",
    "artifacts": {
      "outlinePath": "vault/topics/{slug}/02-outline.md",
      "outputPath": "vault/topics/{slug}/00-overview.md"
    }
  },
  "topic.synthesise.resources": {
    "kinds": [
      "topic"
    ],
    "phase": "Synthesise",
    "effect": "writer",
    "agent": "quasi:synthesis-agent",
    "artifacts": {
      "outlinePath": "vault/topics/{slug}/02-outline.md",
      "outputPath": "vault/topics/{slug}/01-resources.md"
    }
  },
  "topic.audit": {
    "kinds": [
      "topic"
    ],
    "phase": "Audit",
    "effect": "writer",
    "agent": "quasi:audit-agent",
    "artifacts": {
      "target": "{target}"
    }
  },
  "author.discover-books": {
    "kinds": [
      "author"
    ],
    "phase": "Search",
    "effect": "readonly",
    "agent": "quasi:discovery-agent",
    "artifacts": {}
  },
  "author.discover-papers": {
    "kinds": [
      "author"
    ],
    "phase": "Search",
    "effect": "readonly",
    "agent": "quasi:discovery-agent",
    "artifacts": {}
  },
  "author.resolve-membership": {
    "kinds": [
      "author"
    ],
    "phase": "Search",
    "effect": "readonly",
    "agent": "general-purpose",
    "artifacts": {
      "output": "vault/authors/{slug}.md"
    }
  },
  "author.synthesise": {
    "kinds": [
      "author"
    ],
    "phase": "Synthesise",
    "effect": "writer",
    "agent": "quasi:synthesis-agent",
    "artifacts": {
      "output": "vault/authors/{slug}.md"
    }
  },
  "author.audit": {
    "kinds": [
      "author"
    ],
    "phase": "Audit",
    "effect": "writer",
    "agent": "quasi:audit-agent",
    "artifacts": {
      "target": "vault/authors/{slug}.md"
    }
  }
};
