// GENERATED by scripts/build-workflows.mjs. DO NOT EDIT.
// Source of truth: scripts/schemas/ frontmatter models, BodySchema, and operations.py.

export type KindName = "archive" | "topic" | "webpage" | "paper" | "book" | "talk" | "translation" | "author";
export type OperationName = "archive.identify" | "archive.collect" | "archive.audit" | "topic.discover-archives" | "webpage.identify" | "webpage.capture" | "webpage.prepare" | "webpage.analyse" | "webpage.audit" | "material.search" | "paper.acquire" | "paper.prepare" | "paper.ocr" | "paper.analyse" | "paper.audit" | "book.acquire" | "book.prepare" | "book.ocr" | "chapter.analyse" | "book.synthesise" | "book.audit" | "talk.prepare" | "talk.analyse" | "talk.audit" | "translation.prepare" | "topic.recall" | "topic.steer" | "topic.webcard" | "topic.synthesise.overview" | "topic.synthesise.resources" | "topic.audit" | "author.discover-books" | "author.discover-papers" | "author.resolve-membership" | "author.synthesise" | "author.audit";
export type PhaseName = "Search" | "Acquire" | "Audit" | "Prepare" | "Analyse" | "Synthesise" | "Recall";
export type EffectName = "readonly" | "writer";

export type WorkflowContext = Record<string, any>;
export type JsonSchema = Record<string, any>;
export interface ArtifactContract {
  readonly artifact_type: string;
  readonly schema_version: string;
  readonly [key: string]: any;
}
export interface ArtifactTemplates {
  readonly [role: string]: string;
}
export interface OperationDefinition {
  readonly kinds: readonly KindName[];
  readonly phase: PhaseName;
  readonly effect: EffectName;
  readonly agent: string;
  readonly artifacts: ArtifactTemplates;
}

export interface StageIssue {
  code: string;
  operation: OperationName | string;
  summary: string;
  user_question: string | null;
  retryable: boolean;
}
export interface StageTerminalPayload {
  disposition?: string;
  source?: string;
  action?: string;
  write_state?: string;
}
export type StageTerminal =
  | ({ status: "complete"; issue: null } & StageTerminalPayload)
  | ({ status: "needs_input"; issue: StageIssue } & StageTerminalPayload)
  | ({ status: "blocked"; issue: StageIssue } & StageTerminalPayload)
  | ({ status: "failed"; issue: StageIssue } & StageTerminalPayload);
export interface StageReceipt extends Record<string, any> {
  terminal: StageTerminal;
}

export type WriteTarget =
  | { scope: "exact"; path: string }
  | { scope: "subtree"; path: string };

export interface OperationRow {
  readonly operation: OperationName;
  readonly context?: (
    rawContext: any,
    base: WorkflowContext,
  ) => WorkflowContext;
  readonly refs: (context: any) => WorkflowContext;
  readonly payloadProperties: (refs: any) => WorkflowContext;
  readonly terminalPayloads?: (refs: any) => WorkflowContext;
  readonly complete: (
    receipt: StageReceipt,
    context: any,
  ) => boolean;
  readonly envelope: (
    context: any,
    refs: any,
  ) => WorkflowContext;
  readonly promptText?: (request: any) => string;
  readonly writeTargets?: (
    refs: WorkflowContext,
    context: WorkflowContext,
  ) => readonly WriteTarget[];
}
export interface OperationDescriptor extends OperationRow {
  readonly stage: PhaseName;
  readonly effect: EffectName;
  readonly agentType: string;
  readonly artifacts: ArtifactTemplates;
}

export const OPERATION_CATALOG: Readonly<
  Record<OperationName, OperationDefinition>
>;
export const TOPIC_OUTLINE_SUBQUESTIONS_SCHEMA: JsonSchema;
export const TOPIC_ARTIFACT_CONTRACT: ArtifactContract;
export const ARCHIVE_ARTIFACT_CONTRACT: ArtifactContract;
export const AUTHOR_ARTIFACT_CONTRACT: ArtifactContract;
export const PAPER_ARTIFACT_CONTRACT: ArtifactContract;
export const CHAPTER_ARTIFACT_CONTRACT: ArtifactContract;
export const BOOK_ARTIFACT_CONTRACT: ArtifactContract;
export const TALK_ARTIFACT_CONTRACT: ArtifactContract;
export const WEBPAGE_ARTIFACT_CONTRACT: ArtifactContract;
