// GENERATED by scripts/build-workflows.mjs. DO NOT EDIT.
// Source of truth: scripts/schemas/ frontmatter models, BodySchema, and pipeline.py.

export type KindName = "paper" | "book" | "talk" | "translation" | "topic" | "author";
export type StageName = "search" | "acquire" | "prepare" | "analyse" | "audit" | "synthesise" | "recall" | "steer" | "webcard" | "synthesise-overview" | "synthesise-resources" | "discover-books" | "discover-papers" | "resolve-membership";
export type OperationName = "material.search" | "paper.acquire" | "paper.prepare" | "paper.analyse" | "paper.audit" | "book.acquire" | "book.prepare" | "chapter.analyse" | "book.synthesise" | "book.audit" | "talk.prepare" | "talk.analyse" | "talk.audit" | "translation.prepare" | "topic.recall" | "topic.steer" | "topic.webcard" | "topic.synthesise.overview" | "topic.synthesise.resources" | "topic.audit" | "author.discover-books" | "author.discover-papers" | "author.resolve-membership" | "author.synthesise" | "author.audit";
export type PhaseName = "Search" | "Acquire" | "Prepare" | "Analyse" | "Audit" | "Synthesise" | "Recall";
export type EffectName = "readonly" | "writer";
export type CarryFieldName = "selected_input";
export type CarryTargetName = "input";

export type WorkflowContext = Record<string, any>;
export type JsonSchema = Record<string, any>;
export interface ArtifactContract {
  readonly artifact_type: string;
  readonly schema_version: string;
  readonly [key: string]: any;
}
export interface ArtifactTemplates {
  readonly [role: string]: string;
}
export interface PipelineCarry {
  readonly from: StageName;
  readonly field: CarryFieldName;
  readonly to: CarryTargetName;
}
export interface PipelineStage {
  readonly stage: StageName;
  readonly operation: OperationName;
  readonly phase: PhaseName;
  readonly effect: EffectName;
  readonly agent: string;
  readonly artifacts?: ArtifactTemplates;
}
export interface KindDefinition {
  readonly stages: readonly PipelineStage[];
  readonly chain?: {
    readonly sequence: readonly StageName[];
    readonly carries: readonly PipelineCarry[];
  };
}

export interface StageIssue {
  code: string;
  operation: OperationName | string;
  summary: string;
  user_question: string | null;
  retryable: boolean;
}
export interface StageTerminalPayload {
  disposition?: string;
  source?: string;
  action?: string;
  write_state?: string;
}
export type StageTerminal =
  | ({ status: "complete"; issue: null } & StageTerminalPayload)
  | ({ status: "needs_input"; issue: StageIssue } & StageTerminalPayload)
  | ({ status: "blocked"; issue: StageIssue } & StageTerminalPayload)
  | ({ status: "failed"; issue: StageIssue } & StageTerminalPayload);
export interface StageReceipt extends Record<string, any> {
  terminal: StageTerminal;
}

export type WriteTarget =
  | { scope: "exact"; path: string }
  | { scope: "subtree"; path: string };

export interface OperationRow {
  readonly operation: OperationName;
  readonly context?: (
    rawContext: any,
    base: WorkflowContext,
  ) => WorkflowContext;
  readonly refs: (context: any) => WorkflowContext;
  readonly payloadProperties: (refs: any) => WorkflowContext;
  readonly terminalPayloads?: (refs: any) => WorkflowContext;
  readonly complete: (
    receipt: StageReceipt,
    context: any,
  ) => boolean;
  readonly envelope: (
    context: any,
    refs: any,
  ) => WorkflowContext;
  readonly promptText?: (request: any) => string;
  readonly writeTargets?: (
    refs: WorkflowContext,
    context: WorkflowContext,
  ) => readonly WriteTarget[];
}
export interface OperationDescriptor extends OperationRow {
  readonly stage: PhaseName;
  readonly effect: EffectName;
  readonly agentType: string;
  readonly artifacts: ArtifactTemplates;
}

export const PAPER_OPERATION_IDENTITIES: readonly PipelineStage[];
export const BOOK_OPERATION_IDENTITIES: readonly PipelineStage[];
export const TALK_OPERATION_IDENTITIES: readonly PipelineStage[];
export const TRANSLATION_OPERATION_IDENTITIES: readonly PipelineStage[];
export const TOPIC_OPERATION_IDENTITIES: readonly PipelineStage[];
export const AUTHOR_OPERATION_IDENTITIES: readonly PipelineStage[];
export const PIPELINE: Readonly<Record<KindName, KindDefinition>>;
export const TOPIC_OUTLINE_SUBQUESTIONS_SCHEMA: JsonSchema;
export const AUTHOR_ARTIFACT_CONTRACT: ArtifactContract;
export const PAPER_ARTIFACT_CONTRACT: ArtifactContract;
export const CHAPTER_ARTIFACT_CONTRACT: ArtifactContract;
export const BOOK_ARTIFACT_CONTRACT: ArtifactContract;
export const TALK_ARTIFACT_CONTRACT: ArtifactContract;
