#!/usr/bin/env node

import {
	mkdir,
	readFile,
	readdir,
	rename,
	writeFile,
} from "node:fs/promises";
import { homedir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const DEFAULT_PLUGIN_ROOT = resolve(HERE, "..");
const USAGE =
	"Usage: quasi-codex-agents (--project PATH|--user) [--check] [--json]\n";

function parseCli(argv) {
	const options = { check: false, json: false, user: false };
	for (let index = 0; index < argv.length; index += 1) {
		const flag = argv[index];
		if (flag === "--help") {
			options.help = true;
		} else if (flag === "--check") {
			options.check = true;
		} else if (flag === "--json") {
			options.json = true;
		} else if (flag === "--user") {
			options.user = true;
		} else if (flag === "--project" || flag === "--plugin-root") {
			const value = argv[++index];
			if (!value) throw new Error(`missing value for ${flag}`);
			options[flag.slice(2)] = value;
		} else {
			throw new Error(`unexpected argument: ${flag}`);
		}
	}
	return options;
}

function parseAgent(source, path) {
	const match = source.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
	if (!match) throw new Error(`${path}: missing YAML frontmatter`);
	const metadata = {};
	for (const line of match[1].split(/\r?\n/)) {
		const field = line.match(/^([a-zA-Z0-9_-]+):\s*(.*)$/);
		if (field) metadata[field[1]] = field[2].trim();
	}
	for (const required of ["name", "description"]) {
		if (!metadata[required])
			throw new Error(`${path}: missing frontmatter field ${required}`);
	}
	return { ...metadata, body: match[2].trim() };
}

function roleName(agentName) {
	const stem = agentName.replace(/-agent$/, "");
	return `quasi_${stem.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "")}`;
}

function tomlString(value) {
	return JSON.stringify(value);
}

function renderAgent({ agent, sourcePath, version }) {
	if (agent.body.includes("'''"))
		throw new Error(`${sourcePath}: body contains unsupported TOML literal delimiter`);
	const role = roleName(agent.name);
	const capabilities = agent.tools
		? `\nThe canonical role declares these capabilities: ${agent.tools}.`
		: "";
	const instructions = [
		"You are a Codex-native worker role generated from quasi's canonical agent contract.",
		"Use this role only when a quasi workflow delegates a matching worker task.",
		"Do not spawn subagents. The task prompt or driver envelope supplies the project root, exact paths, output schema, and per-call constraints.",
		`Follow the canonical contract below.${capabilities}`,
		"",
		agent.body,
	].join("\n");
	return [
		"# Generated by quasi-codex-agents; edit the source Markdown instead.",
		`# Source: ${sourcePath}`,
		`# Quasi plugin version: ${version}`,
		`name = ${tomlString(role)}`,
		`description = ${tomlString(agent.description)}`,
		"developer_instructions = '''",
		instructions,
		"'''",
		"",
	].join("\n");
}

async function writeAtomic(path, content) {
	const temp = `${path}.tmp-${process.pid}-${Date.now()}`;
	await writeFile(temp, content, "utf8");
	await rename(temp, path);
}

export async function syncCodexAgents({
	pluginRoot = DEFAULT_PLUGIN_ROOT,
	destination,
	check = false,
}) {
	const agentsRoot = join(pluginRoot, "agents");
	const manifest = JSON.parse(
		await readFile(join(pluginRoot, ".codex-plugin", "plugin.json"), "utf8"),
	);
	const files = (await readdir(agentsRoot))
		.filter((name) => name.endsWith(".md"))
		.sort();
	if (!files.length) throw new Error(`no agent definitions found in ${agentsRoot}`);
	if (!check) await mkdir(destination, { recursive: true });

	const results = [];
	for (const file of files) {
		const sourceFile = join(agentsRoot, file);
		const agent = parseAgent(await readFile(sourceFile, "utf8"), sourceFile);
		const role = roleName(agent.name);
		const outputFile = join(destination, `${role}.toml`);
		const rendered = renderAgent({
			agent,
			sourcePath: `agents/${basename(sourceFile)}`,
			version: manifest.version,
		});
		let current = null;
		try {
			current = await readFile(outputFile, "utf8");
		} catch (error) {
			if (error.code !== "ENOENT") throw error;
		}
		const status = current === rendered ? "unchanged" : check ? "outdated" : "written";
		if (status === "written") await writeAtomic(outputFile, rendered);
		results.push({ role, source: `agents/${file}`, path: outputFile, status });
	}
	return {
		destination,
		check,
		ok: results.every((item) => item.status !== "outdated"),
		count: results.length,
		written: results.filter((item) => item.status === "written").length,
		outdated: results.filter((item) => item.status === "outdated").length,
		unchanged: results.filter((item) => item.status === "unchanged").length,
		agents: results,
	};
}

async function main() {
	const cli = parseCli(process.argv.slice(2));
	if (cli.help) {
		process.stdout.write(USAGE);
		return;
	}
	if (Boolean(cli.project) === Boolean(cli.user))
		throw new Error("choose exactly one destination: --project PATH or --user");
	const pluginRoot = resolve(cli["plugin-root"] || DEFAULT_PLUGIN_ROOT);
	const destination = cli.user
		? join(resolve(process.env.CODEX_HOME || join(homedir(), ".codex")), "agents")
		: join(resolve(cli.project), ".codex", "agents");
	const result = await syncCodexAgents({
		pluginRoot,
		destination,
		check: cli.check,
	});
	if (cli.json) {
		process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
	} else {
		const action = cli.check ? "checked" : "synced";
		process.stdout.write(
			`${action} ${result.count} Codex agents in ${result.destination} ` +
				`(${result.written} written, ${result.unchanged} unchanged, ${result.outdated} outdated)\n`,
		);
	}
	if (!result.ok) process.exitCode = 1;
}

if (
	process.argv[1] &&
	resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
	main().catch((error) => {
		process.stderr.write(`${error.message}\n`);
		process.exitCode = 1;
	});
}
